import { Download, Printer, X, CheckCircle2 } from 'lucide-react';

export default function LoanReceipt({ application, onClose }) {
  const date = new Date(application.submittedAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
  const download = () => {
    const text = `KISANSETU LOAN APPLICATION RECEIPT\n\nApplication ID: ${application.id}\nStatus: ${application.status}\nBank: ${application.selectedBank}\nApplicant: ${application.applicantName}\nPhone: ${application.phone}\nLoan type: ${application.loanType}\nCrop/Business: ${application.cropOrBusiness}\nAmount: ₹${Number(application.amount).toLocaleString('en-IN')}\nPurpose: ${application.purpose}\nIncome: ₹${Number(application.income).toLocaleString('en-IN')} / month\nSubmitted: ${date}\n\nThis receipt confirms submission only and is not a loan approval.`;
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${application.id}.txt`; a.click(); URL.revokeObjectURL(url);
  };
  return <div className="modal-backdrop receipt-backdrop"><section className="receipt-modal" id="loan-receipt"><div className="receipt-actions no-print"><button className="icon-button" onClick={onClose}><X size={17}/></button></div><div className="receipt-brand"><CheckCircle2 size={28}/><div><strong>KisanSetu</strong><small>Loan application receipt</small></div></div><div className="receipt-status"><span>Application submitted</span><strong>{application.status}</strong></div><div className="receipt-id"><small>APPLICATION ID</small><strong>{application.id}</strong></div><div className="receipt-grid">{[['Selected bank',application.selectedBank],['Loan amount',`₹${Number(application.amount).toLocaleString('en-IN')}`],['Applicant',application.applicantName],['Phone',application.phone],['Loan type',application.loanType],['Crop / business',application.cropOrBusiness || '—'],['Purpose',application.purpose],['Monthly income',`₹${Number(application.income).toLocaleString('en-IN')}`],['Submitted',date]].map(([label,value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p className="receipt-note">Keep this application ID for status tracking. Submission does not guarantee loan approval; the lender will perform its own verification.</p><div className="receipt-buttons no-print"><button className="outline-button" onClick={download}><Download size={16}/> Download receipt</button><button className="primary-button" onClick={() => window.print()}><Printer size={16}/> Print / Save as PDF</button></div></section></div>;
}
