import { useState } from 'react';

export default function LotModal({ crop, onClose, onSave }) {
  const [form, setForm] = useState({ crop, variety: '', quantity: 100, grade: 'A', askingPrice: 2600, location: 'Niphad, Nashik', harvestDate: '2026-09-02' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); const quantity = Number(form.quantity); if (!Number.isInteger(quantity) || quantity < 1 || quantity > 5000) { setError('Enter a whole quantity from 1 to 5,000 quintals.'); return; } setError(''); setSaving(true); await onSave({ ...form, quantity, askingPrice: Number(form.askingPrice) }); setSaving(false); };
  const update = (key, value) => setForm({ ...form, [key]: value });
  const varieties = form.crop === 'Onion' ? ['Red Onion', 'White Onion', 'N-53'] : form.crop === 'Tomato' ? ['Hybrid', 'Desi', 'Cherry tomato'] : ['Yellow soybean', 'JS-335', 'Other'];
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="lot-title"><form className="lot-modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">SELL YOUR PRODUCE</p><h2 id="lot-title">Create a crop lot</h2></div><button type="button" className="icon-button" aria-label="Close crop lot form" onClick={onClose}>×</button></div><div className="form-grid"><label>Crop<select value={form.crop} onChange={(event) => setForm({ ...form, crop: event.target.value, variety: '' })}><option>Onion</option><option>Tomato</option><option>Soybean</option></select></label><label>Variety <span className="optional">Optional</span><select value={form.variety} onChange={(event) => update('variety', event.target.value)}><option value="">Select variety (optional)</option>{varieties.map((variety) => <option key={variety}>{variety}</option>)}</select></label><label>Quantity (quintal)<input required min="1" max="5000" step="1" type="number" value={form.quantity} onChange={(event) => update('quantity', event.target.value)}/></label><label>Quality grade<select value={form.grade} onChange={(event) => update('grade', event.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label>Asking price (₹/q)<input required min="1" type="number" value={form.askingPrice} onChange={(event) => update('askingPrice', event.target.value)}/></label><label>Pickup location<input required type="text" value={form.location} onChange={(event) => update('location', event.target.value)}/></label><label className="full-width">Harvest date <span className="date-help">Use the date picker — e.g., 02 Sep 2026</span><input required type="date" value={form.harvestDate} onChange={(event) => update('harvestDate', event.target.value)}/></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="primary-button" disabled={saving}>{saving ? 'Creating lot…' : 'Publish crop lot'}</button></div></form></div>;
}
