const en = {
  nav: 'Equipment sharing', eyebrow: 'P2P EQUIPMENT SHARING', title: 'Rent farm machinery from nearby farmers', subtitle: 'List idle machinery, filter available equipment and send rental requests directly between farmers.',
  demoUser: 'Demo user', viewingAs: 'Viewing as', switchUser: 'Switch user', demoUserHint: 'Switch farmers to demonstrate both renter and equipment-owner actions.',
  listEquipment: 'List equipment', filters: 'Filters', type: 'Equipment type', allTypes: 'All types', district: 'District', maxRate: 'Max daily rate', availableFrom: 'Available from', availableTo: 'Available to', applyFilters: 'Apply filters', clearFilters: 'Clear', loading: 'Loading equipment…', unavailable: 'Equipment sharing is temporarily unavailable.', empty: 'No equipment matches these filters.',
  perDay: '/day', deposit: 'Security deposit', condition: 'Condition', available: 'Available', owner: 'Owner', horsepower: '{{value}} HP', rent: 'Rent equipment', yourListing: 'Your listing', deleteListing: 'Delete listing', demo: 'Demo listing',
  myRentals: 'Rental activity', noRentals: 'No rental requests yet.', incoming: 'Incoming request', outgoing: 'Your request', approve: 'Approve', reject: 'Reject', cancel: 'Cancel', complete: 'Mark complete',
  listTitle: 'List agricultural equipment', equipmentName: 'Equipment name', description: 'Description', state: 'State', dailyRate: 'Daily rent (₹)', securityDeposit: 'Security deposit (₹)', horsepowerLabel: 'Horsepower (optional)', publish: 'Publish listing', publishing: 'Publishing…', close: 'Close',
  rentTitle: 'Request rental', startDate: 'Start date', endDate: 'End date', rentalDays: '{{count}} day rental', rentalDays_other: '{{count}} day rental', estimatedRent: 'Estimated rent', requestRental: 'Send rental request', requesting: 'Sending…', rentalNote: 'The owner must approve the request. Security deposit is shown separately.',
  listedSuccess: 'Equipment listed successfully.', rentalSuccess: 'Rental request sent.', deletedSuccess: 'Equipment listing deleted.', statusUpdated: 'Rental status updated.',
  statuses: { requested: 'Requested', approved: 'Approved', rejected: 'Rejected', cancelled: 'Cancelled', completed: 'Completed' },
  types: { Tractor: 'Tractor', Rotavator: 'Rotavator', Harvester: 'Harvester', Seeder: 'Seeder', Sprayer: 'Sprayer', Thresher: 'Thresher', Cultivator: 'Cultivator', Other: 'Other' },
  conditions: { Good: 'Good', 'Very Good': 'Very good', Excellent: 'Excellent' }
};

const translations = {
  en,
  hi: { ...en, nav: 'उपकरण साझा', eyebrow: 'किसान-से-किसान उपकरण', title: 'पास के किसानों से कृषि मशीन किराये पर लें', subtitle: 'खाली मशीन सूचीबद्ध करें, उपलब्ध उपकरण छाँटें और किराये का अनुरोध भेजें।', demoUser: 'डेमो उपयोगकर्ता', viewingAs: 'इस रूप में देख रहे हैं', switchUser: 'उपयोगकर्ता बदलें', demoUserHint: 'किरायेदार और उपकरण मालिक दोनों की प्रक्रिया दिखाने के लिए किसान बदलें।', listEquipment: 'उपकरण सूचीबद्ध करें', filters: 'फ़िल्टर', type: 'उपकरण प्रकार', allTypes: 'सभी प्रकार', district: 'जिला', maxRate: 'अधिकतम दैनिक किराया', availableFrom: 'उपलब्धता शुरू', availableTo: 'उपलब्धता समाप्त', applyFilters: 'फ़िल्टर लागू करें', clearFilters: 'साफ़ करें', loading: 'उपकरण लोड हो रहे हैं…', unavailable: 'उपकरण साझा सेवा अभी उपलब्ध नहीं है।', empty: 'इन फ़िल्टर से कोई उपकरण नहीं मिला।', perDay: '/दिन', deposit: 'सुरक्षा जमा', condition: 'स्थिति', available: 'उपलब्ध', owner: 'मालिक', rent: 'किराये पर लें', yourListing: 'आपकी सूची', deleteListing: 'सूची हटाएँ', demo: 'डेमो सूची', myRentals: 'किराया गतिविधि', noRentals: 'अभी कोई किराया अनुरोध नहीं।', incoming: 'आने वाला अनुरोध', outgoing: 'आपका अनुरोध', approve: 'मंज़ूर', reject: 'अस्वीकार', cancel: 'रद्द', complete: 'पूरा चिह्नित करें', listTitle: 'कृषि उपकरण सूचीबद्ध करें', equipmentName: 'उपकरण नाम', description: 'विवरण', state: 'राज्य', dailyRate: 'दैनिक किराया (₹)', securityDeposit: 'सुरक्षा जमा (₹)', horsepowerLabel: 'हॉर्सपावर (वैकल्पिक)', publish: 'सूची प्रकाशित करें', publishing: 'प्रकाशित हो रहा…', close: 'बंद करें', rentTitle: 'किराया अनुरोध', startDate: 'शुरू तारीख', endDate: 'समाप्त तारीख', estimatedRent: 'अनुमानित किराया', requestRental: 'किराया अनुरोध भेजें', requesting: 'भेजा जा रहा…', rentalNote: 'मालिक को अनुरोध मंज़ूर करना होगा। सुरक्षा जमा अलग दिखाया गया है।', listedSuccess: 'उपकरण सफलतापूर्वक सूचीबद्ध हुआ।', rentalSuccess: 'किराया अनुरोध भेजा गया।', deletedSuccess: 'उपकरण सूची हटाई गई।', statusUpdated: 'किराया स्थिति अपडेट हुई।' },
  mr: { ...en, nav: 'उपकरण शेअरिंग', eyebrow: 'शेतकरी-ते-शेतकरी उपकरण', title: 'जवळच्या शेतकऱ्यांकडून शेती यंत्रे भाड्याने घ्या', subtitle: 'मोकळी यंत्रे सूचीबद्ध करा, उपलब्ध उपकरणे फिल्टर करा आणि भाडे विनंती पाठवा.', demoUser: 'डेमो वापरकर्ता', viewingAs: 'या शेतकऱ्याच्या रूपात', switchUser: 'वापरकर्ता बदला', demoUserHint: 'भाडेकरू आणि उपकरण मालक दोन्ही बाजू दाखवण्यासाठी शेतकरी बदला.', listEquipment: 'उपकरण सूचीबद्ध करा', filters: 'फिल्टर', type: 'उपकरण प्रकार', allTypes: 'सर्व प्रकार', district: 'जिल्हा', maxRate: 'कमाल दैनिक दर', availableFrom: 'पासून उपलब्ध', availableTo: 'पर्यंत उपलब्ध', applyFilters: 'फिल्टर लावा', clearFilters: 'साफ करा', loading: 'उपकरणे लोड होत आहेत…', unavailable: 'उपकरण शेअरिंग सध्या उपलब्ध नाही.', empty: 'या फिल्टरमध्ये उपकरण सापडले नाही.', perDay: '/दिवस', deposit: 'सुरक्षा ठेव', condition: 'स्थिती', available: 'उपलब्ध', owner: 'मालक', rent: 'भाड्याने घ्या', yourListing: 'तुमची सूची', deleteListing: 'सूची हटवा', demo: 'डेमो सूची', myRentals: 'भाडे व्यवहार', noRentals: 'अजून भाडे विनंती नाही.', incoming: 'येणारी विनंती', outgoing: 'तुमची विनंती', approve: 'मंजूर', reject: 'नकार', cancel: 'रद्द', complete: 'पूर्ण करा', listTitle: 'शेती उपकरण सूचीबद्ध करा', equipmentName: 'उपकरणाचे नाव', description: 'वर्णन', state: 'राज्य', dailyRate: 'दैनिक भाडे (₹)', securityDeposit: 'सुरक्षा ठेव (₹)', horsepowerLabel: 'हॉर्सपावर (ऐच्छिक)', publish: 'सूची प्रकाशित करा', publishing: 'प्रकाशित करत आहे…', close: 'बंद', rentTitle: 'भाडे विनंती', startDate: 'सुरुवात तारीख', endDate: 'शेवट तारीख', estimatedRent: 'अंदाजे भाडे', requestRental: 'भाडे विनंती पाठवा', requesting: 'पाठवत आहे…', rentalNote: 'मालकाने विनंती मंजूर करणे आवश्यक आहे. सुरक्षा ठेव वेगळी दाखवली आहे.', listedSuccess: 'उपकरण सूचीबद्ध झाले.', rentalSuccess: 'भाडे विनंती पाठवली.', deletedSuccess: 'उपकरण सूची हटवली.', statusUpdated: 'भाडे स्थिती अपडेट झाली.' },
  ur: { ...en, nav: 'آلات شیئرنگ', eyebrow: 'کسان سے کسان آلات', title: 'قریبی کسانوں سے زرعی مشینری کرائے پر لیں', subtitle: 'فارغ مشینری درج کریں، دستیاب آلات فلٹر کریں اور کرایہ کی درخواست بھیجیں۔', demoUser: 'ڈیمو صارف', viewingAs: 'اس حیثیت سے دیکھ رہے ہیں', switchUser: 'صارف تبدیل کریں', demoUserHint: 'کرایہ دار اور آلات کے مالک دونوں مراحل دکھانے کے لیے کسان تبدیل کریں۔', listEquipment: 'آلات درج کریں', filters: 'فلٹر', type: 'آلات کی قسم', allTypes: 'تمام اقسام', district: 'ضلع', maxRate: 'زیادہ سے زیادہ یومیہ کرایہ', availableFrom: 'دستیاب از', availableTo: 'دستیاب تا', applyFilters: 'فلٹر لگائیں', clearFilters: 'صاف کریں', loading: 'آلات لوڈ ہو رہے ہیں…', unavailable: 'آلات شیئرنگ عارضی طور پر دستیاب نہیں۔', empty: 'کوئی آلات نہیں ملے۔', perDay: '/دن', deposit: 'سیکیورٹی ڈپازٹ', condition: 'حالت', available: 'دستیاب', owner: 'مالک', rent: 'کرائے پر لیں', yourListing: 'آپ کی فہرست', deleteListing: 'فہرست حذف کریں', demo: 'ڈیمو فہرست', myRentals: 'کرایہ سرگرمی', noRentals: 'ابھی کوئی درخواست نہیں۔', incoming: 'موصول درخواست', outgoing: 'آپ کی درخواست', approve: 'منظور', reject: 'مسترد', cancel: 'منسوخ', complete: 'مکمل', listTitle: 'زرعی آلات درج کریں', equipmentName: 'آلات کا نام', description: 'تفصیل', state: 'ریاست', dailyRate: 'یومیہ کرایہ (₹)', securityDeposit: 'سیکیورٹی ڈپازٹ (₹)', horsepowerLabel: 'ہارس پاور (اختیاری)', publish: 'فہرست شائع کریں', publishing: 'شائع ہو رہا…', close: 'بند', rentTitle: 'کرایہ کی درخواست', startDate: 'شروع تاریخ', endDate: 'اختتامی تاریخ', estimatedRent: 'تخمینی کرایہ', requestRental: 'درخواست بھیجیں', requesting: 'بھیجا جا رہا…', rentalNote: 'مالک کو درخواست منظور کرنی ہوگی۔ سیکیورٹی ڈپازٹ الگ ہے۔', listedSuccess: 'آلات درج ہوگئے۔', rentalSuccess: 'کرایہ درخواست بھیج دی گئی۔', deletedSuccess: 'آلات کی فہرست حذف ہوگئی۔', statusUpdated: 'کرایہ کی حالت اپڈیٹ ہوگئی۔' },
  tr: { ...en, nav: 'Ekipman paylaşımı', eyebrow: 'ÇİFTÇİDEN ÇİFTÇİYE EKİPMAN', title: 'Yakındaki çiftçilerden tarım makinesi kiralayın', subtitle: 'Boş makinelerinizi listeleyin, uygun ekipmanı filtreleyin ve kiralama isteği gönderin.', demoUser: 'Demo kullanıcı', viewingAs: 'Şu kullanıcı olarak görüntüleniyor', switchUser: 'Kullanıcı değiştir', demoUserHint: 'Kiracı ve ekipman sahibi akışlarını göstermek için çiftçiyi değiştirin.', listEquipment: 'Ekipman listele', filters: 'Filtreler', type: 'Ekipman türü', allTypes: 'Tüm türler', district: 'İlçe', maxRate: 'Maks. günlük ücret', availableFrom: 'Başlangıç', availableTo: 'Bitiş', applyFilters: 'Filtrele', clearFilters: 'Temizle', loading: 'Ekipman yükleniyor…', unavailable: 'Ekipman paylaşımı geçici olarak kullanılamıyor.', empty: 'Bu filtrelere uygun ekipman yok.', perDay: '/gün', deposit: 'Depozito', condition: 'Durum', available: 'Uygun', owner: 'Sahibi', rent: 'Kirala', yourListing: 'İlanınız', deleteListing: 'İlanı sil', demo: 'Demo ilan', myRentals: 'Kiralama hareketleri', noRentals: 'Henüz kiralama isteği yok.', incoming: 'Gelen istek', outgoing: 'İsteğiniz', approve: 'Onayla', reject: 'Reddet', cancel: 'İptal', complete: 'Tamamlandı', listTitle: 'Tarım ekipmanı listele', equipmentName: 'Ekipman adı', description: 'Açıklama', state: 'Eyalet', dailyRate: 'Günlük kira (₹)', securityDeposit: 'Depozito (₹)', horsepowerLabel: 'Beygir gücü (isteğe bağlı)', publish: 'İlanı yayınla', publishing: 'Yayınlanıyor…', close: 'Kapat', rentTitle: 'Kiralama isteği', startDate: 'Başlangıç tarihi', endDate: 'Bitiş tarihi', estimatedRent: 'Tahmini kira', requestRental: 'İstek gönder', requesting: 'Gönderiliyor…', rentalNote: 'Sahibin isteği onaylaması gerekir. Depozito ayrıca gösterilir.', listedSuccess: 'Ekipman listelendi.', rentalSuccess: 'Kiralama isteği gönderildi.', deletedSuccess: 'Ekipman ilanı silindi.', statusUpdated: 'Kiralama durumu güncellendi.' },
  es: { ...en, nav: 'Compartir maquinaria', eyebrow: 'MAQUINARIA ENTRE AGRICULTORES', title: 'Alquila maquinaria agrícola a agricultores cercanos', subtitle: 'Publica maquinaria inactiva, filtra equipos disponibles y envía solicitudes de alquiler.', demoUser: 'Usuario de demostración', viewingAs: 'Viendo como', switchUser: 'Cambiar usuario', demoUserHint: 'Cambia de agricultor para demostrar las acciones del arrendatario y del propietario.', listEquipment: 'Publicar equipo', filters: 'Filtros', type: 'Tipo de equipo', allTypes: 'Todos', district: 'Distrito', maxRate: 'Máx. por día', availableFrom: 'Disponible desde', availableTo: 'Disponible hasta', applyFilters: 'Aplicar filtros', clearFilters: 'Limpiar', loading: 'Cargando equipos…', unavailable: 'El servicio de maquinaria no está disponible temporalmente.', empty: 'No hay equipos con estos filtros.', perDay: '/día', deposit: 'Depósito', condition: 'Estado', available: 'Disponible', owner: 'Propietario', rent: 'Alquilar', yourListing: 'Tu anuncio', deleteListing: 'Eliminar anuncio', demo: 'Anuncio demo', myRentals: 'Actividad de alquiler', noRentals: 'Aún no hay solicitudes.', incoming: 'Solicitud recibida', outgoing: 'Tu solicitud', approve: 'Aprobar', reject: 'Rechazar', cancel: 'Cancelar', complete: 'Marcar completo', listTitle: 'Publicar maquinaria agrícola', equipmentName: 'Nombre del equipo', description: 'Descripción', state: 'Estado/Región', dailyRate: 'Alquiler diario (₹)', securityDeposit: 'Depósito (₹)', horsepowerLabel: 'Potencia (opcional)', publish: 'Publicar', publishing: 'Publicando…', close: 'Cerrar', rentTitle: 'Solicitar alquiler', startDate: 'Fecha inicial', endDate: 'Fecha final', estimatedRent: 'Alquiler estimado', requestRental: 'Enviar solicitud', requesting: 'Enviando…', rentalNote: 'El propietario debe aprobar la solicitud. El depósito se muestra por separado.', listedSuccess: 'Equipo publicado.', rentalSuccess: 'Solicitud enviada.', deletedSuccess: 'Anuncio eliminado.', statusUpdated: 'Estado de alquiler actualizado.' },
  pa: { ...en, nav: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਸਾਂਝਾ', eyebrow: 'ਕਿਸਾਨ ਤੋਂ ਕਿਸਾਨ ਸਾਜ਼ੋ-ਸਾਮਾਨ', title: 'ਨੇੜਲੇ ਕਿਸਾਨਾਂ ਤੋਂ ਖੇਤੀ ਮਸ਼ੀਨਰੀ ਕਿਰਾਏ ਤੇ ਲਵੋ', subtitle: 'ਖਾਲੀ ਮਸ਼ੀਨਰੀ ਲਿਸਟ ਕਰੋ, ਉਪਲਬਧ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਫਿਲਟਰ ਕਰੋ ਅਤੇ ਕਿਰਾਏ ਦੀ ਬੇਨਤੀ ਭੇਜੋ।', demoUser: 'ਡੈਮੋ ਯੂਜ਼ਰ', viewingAs: 'ਇਸ ਵਜੋਂ ਦੇਖ ਰਹੇ ਹੋ', switchUser: 'ਯੂਜ਼ਰ ਬਦਲੋ', demoUserHint: 'ਕਿਰਾਏਦਾਰ ਅਤੇ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਮਾਲਕ ਦੋਵੇਂ ਪੱਖ ਦਿਖਾਉਣ ਲਈ ਕਿਸਾਨ ਬਦਲੋ।', listEquipment: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਲਿਸਟ ਕਰੋ', filters: 'ਫਿਲਟਰ', type: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਦੀ ਕਿਸਮ', allTypes: 'ਸਭ ਕਿਸਮਾਂ', district: 'ਜ਼ਿਲ੍ਹਾ', maxRate: 'ਵੱਧ ਤੋਂ ਵੱਧ ਦਿਨ ਦਾ ਕਿਰਾਇਆ', availableFrom: 'ਤੋਂ ਉਪਲਬਧ', availableTo: 'ਤੱਕ ਉਪਲਬਧ', applyFilters: 'ਫਿਲਟਰ ਲਗਾਓ', clearFilters: 'ਸਾਫ਼ ਕਰੋ', loading: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਲੋਡ ਹੋ ਰਿਹਾ…', unavailable: 'ਸੇਵਾ ਅਸਥਾਈ ਤੌਰ ਤੇ ਉਪਲਬਧ ਨਹੀਂ।', empty: 'ਕੋਈ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਨਹੀਂ ਮਿਲਿਆ।', perDay: '/ਦਿਨ', deposit: 'ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ', condition: 'ਹਾਲਤ', available: 'ਉਪਲਬਧ', owner: 'ਮਾਲਕ', rent: 'ਕਿਰਾਏ ਤੇ ਲਵੋ', yourListing: 'ਤੁਹਾਡੀ ਲਿਸਟ', deleteListing: 'ਲਿਸਟ ਹਟਾਓ', demo: 'ਡੈਮੋ ਲਿਸਟ', myRentals: 'ਕਿਰਾਇਆ ਗਤੀਵਿਧੀ', noRentals: 'ਹਾਲੇ ਕੋਈ ਬੇਨਤੀ ਨਹੀਂ।', incoming: 'ਆਈ ਬੇਨਤੀ', outgoing: 'ਤੁਹਾਡੀ ਬੇਨਤੀ', approve: 'ਮਨਜ਼ੂਰ', reject: 'ਰੱਦ', cancel: 'ਰੱਦ ਕਰੋ', complete: 'ਪੂਰਾ', listTitle: 'ਖੇਤੀ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਲਿਸਟ ਕਰੋ', equipmentName: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਨਾਮ', description: 'ਵੇਰਵਾ', state: 'ਰਾਜ', dailyRate: 'ਦਿਨ ਦਾ ਕਿਰਾਇਆ (₹)', securityDeposit: 'ਸੁਰੱਖਿਆ ਜਮ੍ਹਾਂ (₹)', horsepowerLabel: 'ਹਾਰਸਪਾਵਰ (ਵਿਕਲਪਿਕ)', publish: 'ਲਿਸਟ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ', publishing: 'ਪ੍ਰਕਾਸ਼ਿਤ…', close: 'ਬੰਦ', rentTitle: 'ਕਿਰਾਏ ਦੀ ਬੇਨਤੀ', startDate: 'ਸ਼ੁਰੂ ਮਿਤੀ', endDate: 'ਅੰਤ ਮਿਤੀ', estimatedRent: 'ਅਨੁਮਾਨਿਤ ਕਿਰਾਇਆ', requestRental: 'ਬੇਨਤੀ ਭੇਜੋ', requesting: 'ਭੇਜ ਰਿਹਾ…', rentalNote: 'ਮਾਲਕ ਦੀ ਮਨਜ਼ੂਰੀ ਲੋੜੀਂਦੀ ਹੈ। ਜਮ੍ਹਾਂ ਵੱਖਰਾ ਹੈ।', listedSuccess: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਲਿਸਟ ਹੋ ਗਿਆ।', rentalSuccess: 'ਬੇਨਤੀ ਭੇਜੀ ਗਈ।', deletedSuccess: 'ਲਿਸਟ ਹਟਾਈ ਗਈ।', statusUpdated: 'ਕਿਰਾਇਆ ਸਥਿਤੀ ਅੱਪਡੇਟ ਹੋਈ।' },
  or: { ...en, nav: 'ଉପକରଣ ଭାଗିଦାରୀ', eyebrow: 'ଚାଷୀ-ଚାଷୀ ଉପକରଣ', title: 'ନିକଟସ୍ଥ ଚାଷୀଙ୍କଠାରୁ କୃଷି ଯନ୍ତ୍ର ଭଡ଼ା ନିଅନ୍ତୁ', subtitle: 'ଖାଲି ଯନ୍ତ୍ର ତାଲିକାଭୁକ୍ତ କରନ୍ତୁ, ଉପଲବ୍ଧ ଉପକରଣ ଫିଲ୍ଟର କରନ୍ତୁ ଏବଂ ଭଡ଼ା ଅନୁରୋଧ ପଠାନ୍ତୁ।', demoUser: 'ଡେମୋ ବ୍ୟବହାରକାରୀ', viewingAs: 'ଏହି ଭାବେ ଦେଖୁଛନ୍ତି', switchUser: 'ବ୍ୟବହାରକାରୀ ବଦଳାନ୍ତୁ', demoUserHint: 'ଭଡା ନେଉଥିବା ଓ ଯନ୍ତ୍ର ମାଲିକ—ଦୁଇ ପକ୍ଷର କାର୍ଯ୍ୟ ଦେଖାଇବା ପାଇଁ କୃଷକ ବଦଳାନ୍ତୁ।', listEquipment: 'ଉପକରଣ ତାଲିକାଭୁକ୍ତ', filters: 'ଫିଲ୍ଟର', type: 'ଉପକରଣ ପ୍ରକାର', allTypes: 'ସମସ୍ତ ପ୍ରକାର', district: 'ଜିଲ୍ଲା', maxRate: 'ସର୍ବାଧିକ ଦୈନିକ ଭଡ଼ା', availableFrom: 'ଉପଲବ୍ଧ ଆରମ୍ଭ', availableTo: 'ଉପଲବ୍ଧ ଶେଷ', applyFilters: 'ଫିଲ୍ଟର ଲାଗୁ', clearFilters: 'ସଫା', loading: 'ଉପକରଣ ଲୋଡ୍ ହେଉଛି…', unavailable: 'ଉପକରଣ ଭାଗିଦାରୀ ସାମୟିକ ଭାବେ ଉପଲବ୍ଧ ନାହିଁ।', empty: 'ଏହି ଫିଲ୍ଟରରେ ଉପକରଣ ନାହିଁ।', perDay: '/ଦିନ', deposit: 'ସୁରକ୍ଷା ଜମା', condition: 'ଅବସ୍ଥା', available: 'ଉପଲବ୍ଧ', owner: 'ମାଲିକ', rent: 'ଭଡ଼ା ନିଅନ୍ତୁ', yourListing: 'ଆପଣଙ୍କ ତାଲିକା', deleteListing: 'ତାଲିକା ହଟାନ୍ତୁ', demo: 'ଡେମୋ ତାଲିକା', myRentals: 'ଭଡ଼ା କାର୍ଯ୍ୟକଳାପ', noRentals: 'ଏପର୍ଯ୍ୟନ୍ତ ଭଡ଼ା ଅନୁରୋଧ ନାହିଁ।', incoming: 'ଆସିଥିବା ଅନୁରୋଧ', outgoing: 'ଆପଣଙ୍କ ଅନୁରୋଧ', approve: 'ମଞ୍ଜୁର', reject: 'ପ୍ରତ୍ୟାଖ୍ୟାନ', cancel: 'ବାତିଲ', complete: 'ସମ୍ପୂର୍ଣ୍ଣ', listTitle: 'କୃଷି ଉପକରଣ ତାଲିକାଭୁକ୍ତ କରନ୍ତୁ', equipmentName: 'ଉପକରଣ ନାମ', description: 'ବିବରଣୀ', state: 'ରାଜ୍ୟ', dailyRate: 'ଦୈନିକ ଭଡ଼ା (₹)', securityDeposit: 'ସୁରକ୍ଷା ଜମା (₹)', horsepowerLabel: 'ହର୍ସପାୱର (ଇଚ୍ଛାଧୀନ)', publish: 'ପ୍ରକାଶ କରନ୍ତୁ', publishing: 'ପ୍ରକାଶ ହେଉଛି…', close: 'ବନ୍ଦ', rentTitle: 'ଭଡ଼ା ଅନୁରୋଧ', startDate: 'ଆରମ୍ଭ ତାରିଖ', endDate: 'ଶେଷ ତାରିଖ', estimatedRent: 'ଆନୁମାନିକ ଭଡ଼ା', requestRental: 'ଅନୁରୋଧ ପଠାନ୍ତୁ', requesting: 'ପଠାଯାଉଛି…', rentalNote: 'ମାଲିକଙ୍କ ମଞ୍ଜୁରି ଆବଶ୍ୟକ। ସୁରକ୍ଷା ଜମା ଅଲଗା।', listedSuccess: 'ଉପକରଣ ତାଲିକାଭୁକ୍ତ ହେଲା।', rentalSuccess: 'ଭଡ଼ା ଅନୁରୋଧ ପଠାଗଲା।', deletedSuccess: 'ତାଲିକା ହଟାଗଲା।', statusUpdated: 'ଭଡ଼ା ସ୍ଥିତି ଅପଡେଟ୍ ହେଲା।' },
  bn: { ...en, nav: 'যন্ত্র ভাগাভাগি', eyebrow: 'কৃষক থেকে কৃষক যন্ত্র', title: 'কাছের কৃষকের কাছ থেকে কৃষিযন্ত্র ভাড়া নিন', subtitle: 'অব্যবহৃত যন্ত্র তালিকাভুক্ত করুন, উপলভ্য যন্ত্র ফিল্টার করুন এবং ভাড়ার অনুরোধ পাঠান।', demoUser: 'ডেমো ব্যবহারকারী', viewingAs: 'যার হিসেবে দেখছেন', switchUser: 'ব্যবহারকারী বদলান', demoUserHint: 'ভাড়াটে ও যন্ত্রের মালিক—দুই দিকের কাজ দেখাতে কৃষক বদলান।', listEquipment: 'যন্ত্র তালিকাভুক্ত করুন', filters: 'ফিল্টার', type: 'যন্ত্রের ধরন', allTypes: 'সব ধরন', district: 'জেলা', maxRate: 'সর্বোচ্চ দৈনিক ভাড়া', availableFrom: 'উপলভ্য শুরু', availableTo: 'উপলভ্য শেষ', applyFilters: 'ফিল্টার প্রয়োগ', clearFilters: 'সাফ', loading: 'যন্ত্র লোড হচ্ছে…', unavailable: 'যন্ত্র ভাগাভাগি সাময়িকভাবে উপলভ্য নয়।', empty: 'কোনো যন্ত্র পাওয়া যায়নি।', perDay: '/দিন', deposit: 'নিরাপত্তা জামানত', condition: 'অবস্থা', available: 'উপলভ্য', owner: 'মালিক', rent: 'ভাড়া নিন', yourListing: 'আপনার তালিকা', deleteListing: 'তালিকা মুছুন', demo: 'ডেমো তালিকা', myRentals: 'ভাড়া কার্যক্রম', noRentals: 'এখনও কোনো অনুরোধ নেই।', incoming: 'আসা অনুরোধ', outgoing: 'আপনার অনুরোধ', approve: 'অনুমোদন', reject: 'প্রত্যাখ্যান', cancel: 'বাতিল', complete: 'সম্পন্ন', listTitle: 'কৃষিযন্ত্র তালিকাভুক্ত করুন', equipmentName: 'যন্ত্রের নাম', description: 'বিবরণ', state: 'রাজ্য', dailyRate: 'দৈনিক ভাড়া (₹)', securityDeposit: 'নিরাপত্তা জামানত (₹)', horsepowerLabel: 'হর্সপাওয়ার (ঐচ্ছিক)', publish: 'তালিকা প্রকাশ', publishing: 'প্রকাশ হচ্ছে…', close: 'বন্ধ', rentTitle: 'ভাড়ার অনুরোধ', startDate: 'শুরুর তারিখ', endDate: 'শেষ তারিখ', estimatedRent: 'আনুমানিক ভাড়া', requestRental: 'অনুরোধ পাঠান', requesting: 'পাঠানো হচ্ছে…', rentalNote: 'মালিকের অনুমোদন দরকার। জামানত আলাদা দেখানো হয়েছে।', listedSuccess: 'যন্ত্র তালিকাভুক্ত হয়েছে।', rentalSuccess: 'ভাড়ার অনুরোধ পাঠানো হয়েছে।', deletedSuccess: 'তালিকা মুছে ফেলা হয়েছে।', statusUpdated: 'ভাড়ার অবস্থা আপডেট হয়েছে।' },
  gu: { ...en, nav: 'સાધન શેરિંગ', eyebrow: 'ખેડૂતથી ખેડૂત સાધન', title: 'નજીકના ખેડૂતો પાસેથી કૃષિ મશીનરી ભાડે લો', subtitle: 'ખાલી મશીનરી સૂચિબદ્ધ કરો, ઉપલબ્ધ સાધનો ફિલ્ટર કરો અને ભાડાની વિનંતી મોકલો.', demoUser: 'ડેમો વપરાશકર્તા', viewingAs: 'આ તરીકે જોઈ રહ્યા છો', switchUser: 'વપરાશકર્તા બદલો', demoUserHint: 'ભાડે લેનાર અને સાધન માલિક બંનેની પ્રક્રિયા બતાવવા ખેડૂત બદલો.', listEquipment: 'સાધન સૂચિબદ્ધ કરો', filters: 'ફિલ્ટર', type: 'સાધન પ્રકાર', allTypes: 'બધા પ્રકાર', district: 'જિલ્લો', maxRate: 'મહત્તમ દૈનિક ભાડું', availableFrom: 'થી ઉપલબ્ધ', availableTo: 'સુધી ઉપલબ્ધ', applyFilters: 'ફિલ્ટર લાગુ', clearFilters: 'સાફ', loading: 'સાધનો લોડ થઈ રહ્યા છે…', unavailable: 'સાધન શેરિંગ અસ્થાયી રીતે ઉપલબ્ધ નથી.', empty: 'કોઈ સાધન મળ્યું નથી.', perDay: '/દિવસ', deposit: 'સિક્યુરિટી ડિપોઝિટ', condition: 'સ્થિતિ', available: 'ઉપલબ્ધ', owner: 'માલિક', rent: 'ભાડે લો', yourListing: 'તમારી સૂચિ', deleteListing: 'સૂચિ કાઢો', demo: 'ડેમો સૂચિ', myRentals: 'ભાડા પ્રવૃત્તિ', noRentals: 'હજુ કોઈ વિનંતી નથી.', incoming: 'આવતી વિનંતી', outgoing: 'તમારી વિનંતી', approve: 'મંજૂર', reject: 'નકારો', cancel: 'રદ', complete: 'પૂર્ણ', listTitle: 'કૃષિ સાધન સૂચિબદ્ધ કરો', equipmentName: 'સાધન નામ', description: 'વર્ણન', state: 'રાજ્ય', dailyRate: 'દૈનિક ભાડું (₹)', securityDeposit: 'સિક્યુરિટી ડિપોઝિટ (₹)', horsepowerLabel: 'હોર્સપાવર (વૈકલ્પિક)', publish: 'સૂચિ પ્રકાશિત કરો', publishing: 'પ્રકાશિત…', close: 'બંધ', rentTitle: 'ભાડાની વિનંતી', startDate: 'શરૂ તારીખ', endDate: 'અંત તારીખ', estimatedRent: 'અંદાજિત ભાડું', requestRental: 'વિનંતી મોકલો', requesting: 'મોકલી રહ્યું…', rentalNote: 'માલિકની મંજૂરી જરૂરી છે. ડિપોઝિટ અલગ છે.', listedSuccess: 'સાધન સૂચિબદ્ધ થયું.', rentalSuccess: 'ભાડાની વિનંતી મોકલાઈ.', deletedSuccess: 'સૂચિ કાઢી.', statusUpdated: 'ભાડા સ્થિતિ અપડેટ થઈ.' },
  te: { ...en, nav: 'పరికరాల భాగస్వామ్యం', eyebrow: 'రైతు-రైతు పరికరాలు', title: 'సమీప రైతుల నుంచి వ్యవసాయ యంత్రాలు అద్దెకు తీసుకోండి', subtitle: 'ఖాళీ యంత్రాలను జాబితా చేయండి, అందుబాటులో ఉన్న పరికరాలను ఫిల్టర్ చేసి అద్దె అభ్యర్థన పంపండి.', demoUser: 'డెమో వినియోగదారు', viewingAs: 'ఈ వినియోగదారుగా చూస్తున్నారు', switchUser: 'వినియోగదారుని మార్చండి', demoUserHint: 'అద్దెదారు మరియు పరికర యజమాని రెండు వైపుల చర్యలను చూపడానికి రైతును మార్చండి.', listEquipment: 'పరికరం జాబితా చేయండి', filters: 'ఫిల్టర్లు', type: 'పరికరం రకం', allTypes: 'అన్ని రకాలు', district: 'జిల్లా', maxRate: 'గరిష్ఠ రోజువారీ అద్దె', availableFrom: 'అందుబాటు ప్రారంభం', availableTo: 'అందుబాటు ముగింపు', applyFilters: 'ఫిల్టర్లు వర్తించు', clearFilters: 'క్లియర్', loading: 'పరికరాలు లోడ్ అవుతున్నాయి…', unavailable: 'పరికరాల భాగస్వామ్యం తాత్కాలికంగా అందుబాటులో లేదు.', empty: 'పరికరాలు లభించలేదు.', perDay: '/రోజు', deposit: 'భద్రతా డిపాజిట్', condition: 'స్థితి', available: 'అందుబాటులో', owner: 'యజమాని', rent: 'అద్దెకు తీసుకోండి', yourListing: 'మీ జాబితా', deleteListing: 'జాబితా తొలగించు', demo: 'డెమో జాబితా', myRentals: 'అద్దె కార్యకలాపం', noRentals: 'ఇంకా అభ్యర్థనలు లేవు.', incoming: 'వచ్చిన అభ్యర్థన', outgoing: 'మీ అభ్యర్థన', approve: 'ఆమోదించు', reject: 'తిరస్కరించు', cancel: 'రద్దు', complete: 'పూర్తి', listTitle: 'వ్యవసాయ పరికరం జాబితా చేయండి', equipmentName: 'పరికరం పేరు', description: 'వివరణ', state: 'రాష్ట్రం', dailyRate: 'రోజువారీ అద్దె (₹)', securityDeposit: 'భద్రతా డిపాజిట్ (₹)', horsepowerLabel: 'హార్స్‌పవర్ (ఐచ్ఛికం)', publish: 'జాబితా ప్రచురించు', publishing: 'ప్రచురిస్తోంది…', close: 'మూసివేయి', rentTitle: 'అద్దె అభ్యర్థన', startDate: 'ప్రారంభ తేదీ', endDate: 'ముగింపు తేదీ', estimatedRent: 'అంచనా అద్దె', requestRental: 'అభ్యర్థన పంపు', requesting: 'పంపుతోంది…', rentalNote: 'యజమాని ఆమోదం అవసరం. డిపాజిట్ వేరుగా చూపబడుతుంది.', listedSuccess: 'పరికరం జాబితా అయ్యింది.', rentalSuccess: 'అద్దె అభ్యర్థన పంపబడింది.', deletedSuccess: 'జాబితా తొలగించబడింది.', statusUpdated: 'అద్దె స్థితి నవీకరించబడింది.' },
  ta: { ...en, nav: 'உபகரண பகிர்வு', eyebrow: 'விவசாயி-விவசாயி உபகரணம்', title: 'அருகிலுள்ள விவசாயிகளிடமிருந்து வேளாண் இயந்திரங்களை வாடகைக்கு எடுக்கவும்', subtitle: 'பயன்பாடில்லாத இயந்திரங்களை பட்டியலிட்டு, கிடைக்கும் உபகரணங்களை வடிகட்டி வாடகை கோரிக்கை அனுப்புங்கள்.', demoUser: 'டெமோ பயனர்', viewingAs: 'இவராக பார்க்கப்படுகிறது', switchUser: 'பயனரை மாற்று', demoUserHint: 'வாடகையாளர் மற்றும் உபகரண உரிமையாளர் இரு பக்க செயல்களையும் காட்ட விவசாயியை மாற்றுங்கள்.', listEquipment: 'உபகரணம் பட்டியலிடு', filters: 'வடிகட்டிகள்', type: 'உபகரண வகை', allTypes: 'அனைத்து வகைகள்', district: 'மாவட்டம்', maxRate: 'அதிகபட்ச தின வாடகை', availableFrom: 'கிடைக்கும் தொடக்கம்', availableTo: 'கிடைக்கும் முடிவு', applyFilters: 'வடிகட்டு', clearFilters: 'அழி', loading: 'உபகரணங்கள் ஏற்றப்படுகின்றன…', unavailable: 'உபகரண பகிர்வு தற்காலிகமாக கிடைக்கவில்லை.', empty: 'பொருத்தமான உபகரணம் இல்லை.', perDay: '/நாள்', deposit: 'பாதுகாப்பு வைப்பு', condition: 'நிலை', available: 'கிடைக்கும்', owner: 'உரிமையாளர்', rent: 'வாடகைக்கு எடு', yourListing: 'உங்கள் பட்டியல்', deleteListing: 'பட்டியல் நீக்கு', demo: 'டெமோ பட்டியல்', myRentals: 'வாடகை செயல்பாடு', noRentals: 'இன்னும் கோரிக்கைகள் இல்லை.', incoming: 'வரும் கோரிக்கை', outgoing: 'உங்கள் கோரிக்கை', approve: 'ஒப்புதல்', reject: 'நிராகரி', cancel: 'ரத்து', complete: 'முடிந்தது', listTitle: 'வேளாண் உபகரணம் பட்டியலிடு', equipmentName: 'உபகரண பெயர்', description: 'விவரம்', state: 'மாநிலம்', dailyRate: 'தின வாடகை (₹)', securityDeposit: 'பாதுகாப்பு வைப்பு (₹)', horsepowerLabel: 'ஹார்ஸ்பவர் (விருப்பம்)', publish: 'பட்டியல் வெளியிடு', publishing: 'வெளியிடுகிறது…', close: 'மூடு', rentTitle: 'வாடகை கோரிக்கை', startDate: 'தொடக்க தேதி', endDate: 'முடிவு தேதி', estimatedRent: 'மதிப்பிடப்பட்ட வாடகை', requestRental: 'கோரிக்கை அனுப்பு', requesting: 'அனுப்புகிறது…', rentalNote: 'உரிமையாளர் ஒப்புதல் தேவை. வைப்பு தனியாக காட்டப்படும்.', listedSuccess: 'உபகரணம் பட்டியலிடப்பட்டது.', rentalSuccess: 'வாடகை கோரிக்கை அனுப்பப்பட்டது.', deletedSuccess: 'பட்டியல் நீக்கப்பட்டது.', statusUpdated: 'வாடகை நிலை புதுப்பிக்கப்பட்டது.' }
};

const assistantEquipmentTranslations = {
  en: {
    assistantTitle: 'Equipment sharing', openMarketplace: 'Open equipment sharing',
    assistantIntroAddon: 'I can also help with farm-equipment listings, rentals and owner approvals.',
    assistantOverview: 'Farmers can list idle machinery, filter available equipment, request rentals, and owners can approve or reject requests.',
    assistantRentHelp: 'Open Equipment sharing, choose a machine, press Rent equipment, select the dates and send the request. The owner must approve it.',
    assistantListHelp: 'Open Equipment sharing and choose List equipment. Add the machine details, location, daily rent, deposit and availability dates.',
    assistantApprovalHelp: 'Incoming requests appear in Rental activity. Switch to the equipment owner from the profile card, then choose Approve or Reject.',
    assistantStatusSummary: '{{incoming}} incoming requested · {{outgoing}} outgoing · {{approved}} approved.',
    assistantCurrentUser: 'Equipment demo account: {{name}}.',
    assistantAvailable: 'Available now: {{items}}.', assistantNoAvailable: 'No matching equipment is currently available.'
  },
  hi: {
    assistantTitle: 'उपकरण साझा', openMarketplace: 'उपकरण साझा खोलें', assistantIntroAddon: 'मैं कृषि उपकरण सूची, किराया और मालिक की मंज़ूरी में भी मदद कर सकता हूँ।',
    assistantOverview: 'किसान खाली मशीनें सूचीबद्ध कर सकते हैं, उपलब्ध उपकरण छाँट सकते हैं, किराया अनुरोध भेज सकते हैं और मालिक अनुरोध मंज़ूर या अस्वीकार कर सकते हैं।',
    assistantRentHelp: 'उपकरण साझा खोलें, मशीन चुनें, किराये पर लें दबाएँ, तारीखें चुनें और अनुरोध भेजें। मालिक को इसे मंज़ूर करना होगा।',
    assistantListHelp: 'उपकरण साझा खोलें और उपकरण सूचीबद्ध करें चुनें। मशीन, स्थान, दैनिक किराया, जमा और उपलब्धता की जानकारी भरें।',
    assistantApprovalHelp: 'आने वाले अनुरोध किराया गतिविधि में दिखते हैं। प्रोफ़ाइल कार्ड से उपकरण मालिक पर जाएँ, फिर मंज़ूर या अस्वीकार चुनें।',
    assistantStatusSummary: '{{incoming}} आने वाले अनुरोध · {{outgoing}} भेजे गए · {{approved}} मंज़ूर।', assistantCurrentUser: 'उपकरण डेमो खाता: {{name}}।',
    assistantAvailable: 'अभी उपलब्ध: {{items}}।', assistantNoAvailable: 'अभी कोई मिलान वाला उपकरण उपलब्ध नहीं है।'
  },
  mr: {
    assistantTitle: 'उपकरण शेअरिंग', openMarketplace: 'उपकरण शेअरिंग उघडा', assistantIntroAddon: 'मी शेती उपकरणांची सूची, भाडे आणि मालक मंजुरीबाबतही मदत करू शकतो.',
    assistantOverview: 'शेतकरी मोकळी यंत्रे सूचीबद्ध करू शकतात, उपलब्ध उपकरणे शोधू शकतात, भाडे विनंती पाठवू शकतात आणि मालक विनंती मंजूर किंवा नाकारू शकतात.',
    assistantRentHelp: 'उपकरण शेअरिंग उघडा, यंत्र निवडा, भाड्याने घ्या दाबा, तारखा निवडा आणि विनंती पाठवा. मालकाची मंजुरी आवश्यक आहे.',
    assistantListHelp: 'उपकरण शेअरिंग उघडा आणि उपकरण सूचीबद्ध करा निवडा. यंत्र, ठिकाण, दैनिक भाडे, ठेव आणि उपलब्धता भरा.',
    assistantApprovalHelp: 'येणाऱ्या विनंत्या भाडे व्यवहारात दिसतात. प्रोफाइल कार्डमधून उपकरण मालकावर स्विच करा आणि मंजूर किंवा नकार निवडा.',
    assistantStatusSummary: '{{incoming}} येणाऱ्या · {{outgoing}} पाठवलेल्या · {{approved}} मंजूर.', assistantCurrentUser: 'उपकरण डेमो खाते: {{name}}.',
    assistantAvailable: 'सध्या उपलब्ध: {{items}}.', assistantNoAvailable: 'सध्या जुळणारे उपकरण उपलब्ध नाही.'
  },
  ur: {
    assistantTitle: 'آلات شیئرنگ', openMarketplace: 'آلات شیئرنگ کھولیں', assistantIntroAddon: 'میں زرعی آلات کی فہرست، کرایہ اور مالک کی منظوری میں بھی مدد کر سکتا ہوں۔',
    assistantOverview: 'کسان فارغ مشینری درج کر سکتے ہیں، دستیاب آلات فلٹر کر سکتے ہیں، کرایہ کی درخواست بھیج سکتے ہیں اور مالک درخواست منظور یا مسترد کر سکتا ہے۔',
    assistantRentHelp: 'آلات شیئرنگ کھولیں، مشین منتخب کریں، کرائے پر لیں دبائیں، تاریخیں منتخب کریں اور درخواست بھیجیں۔ مالک کی منظوری ضروری ہے۔',
    assistantListHelp: 'آلات شیئرنگ کھولیں اور آلات درج کریں منتخب کریں۔ مشین، مقام، یومیہ کرایہ، ڈپازٹ اور دستیابی شامل کریں۔',
    assistantApprovalHelp: 'موصول درخواستیں کرایہ سرگرمی میں نظر آتی ہیں۔ پروفائل کارڈ سے آلات کے مالک پر سوئچ کریں، پھر منظور یا مسترد کریں۔',
    assistantStatusSummary: '{{incoming}} موصول · {{outgoing}} بھیجی گئیں · {{approved}} منظور۔', assistantCurrentUser: 'آلات ڈیمو اکاؤنٹ: {{name}}۔',
    assistantAvailable: 'ابھی دستیاب: {{items}}۔', assistantNoAvailable: 'فی الحال کوئی موزوں آلات دستیاب نہیں۔'
  },
  tr: {
    assistantTitle: 'Ekipman paylaşımı', openMarketplace: 'Ekipman paylaşımını aç', assistantIntroAddon: 'Tarım ekipmanı ilanları, kiralamalar ve sahip onaylarında da yardımcı olabilirim.',
    assistantOverview: 'Çiftçiler boş makineleri listeleyebilir, uygun ekipmanı filtreleyebilir, kiralama isteği gönderebilir; sahipler de isteği onaylayabilir veya reddedebilir.',
    assistantRentHelp: 'Ekipman paylaşımını açın, bir makine seçin, Kirala düğmesine basın, tarihleri seçip isteği gönderin. Sahibin onayı gerekir.',
    assistantListHelp: 'Ekipman paylaşımını açın ve Ekipman listele seçeneğini kullanın. Makine, konum, günlük ücret, depozito ve uygunluk bilgilerini girin.',
    assistantApprovalHelp: 'Gelen istekler Kiralama hareketlerinde görünür. Profil kartından ekipman sahibine geçin, sonra Onayla veya Reddet seçin.',
    assistantStatusSummary: '{{incoming}} gelen · {{outgoing}} giden · {{approved}} onaylı.', assistantCurrentUser: 'Ekipman demo hesabı: {{name}}.',
    assistantAvailable: 'Şu anda uygun: {{items}}.', assistantNoAvailable: 'Şu anda eşleşen ekipman yok.'
  },
  es: {
    assistantTitle: 'Compartir maquinaria', openMarketplace: 'Abrir maquinaria compartida', assistantIntroAddon: 'También puedo ayudar con anuncios, alquileres y aprobaciones de maquinaria agrícola.',
    assistantOverview: 'Los agricultores pueden publicar maquinaria inactiva, filtrar equipos disponibles, solicitar alquileres y los propietarios pueden aprobar o rechazar solicitudes.',
    assistantRentHelp: 'Abre Compartir maquinaria, elige una máquina, pulsa Alquilar, selecciona las fechas y envía la solicitud. El propietario debe aprobarla.',
    assistantListHelp: 'Abre Compartir maquinaria y elige Publicar equipo. Añade máquina, ubicación, alquiler diario, depósito y fechas disponibles.',
    assistantApprovalHelp: 'Las solicitudes recibidas aparecen en Actividad de alquiler. Cambia al propietario desde la tarjeta de perfil y pulsa Aprobar o Rechazar.',
    assistantStatusSummary: '{{incoming}} recibidas · {{outgoing}} enviadas · {{approved}} aprobadas.', assistantCurrentUser: 'Cuenta demo de maquinaria: {{name}}.',
    assistantAvailable: 'Disponible ahora: {{items}}.', assistantNoAvailable: 'No hay maquinaria coincidente disponible ahora.'
  },
  pa: {
    assistantTitle: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਸਾਂਝਾ', openMarketplace: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਸਾਂਝਾ ਖੋਲ੍ਹੋ', assistantIntroAddon: 'ਮੈਂ ਖੇਤੀ ਮਸ਼ੀਨਰੀ ਦੀ ਲਿਸਟਿੰਗ, ਕਿਰਾਏ ਅਤੇ ਮਾਲਕ ਦੀ ਮਨਜ਼ੂਰੀ ਵਿੱਚ ਵੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।',
    assistantOverview: 'ਕਿਸਾਨ ਖਾਲੀ ਮਸ਼ੀਨਰੀ ਲਿਸਟ ਕਰ ਸਕਦੇ ਹਨ, ਉਪਲਬਧ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਫਿਲਟਰ ਕਰ ਸਕਦੇ ਹਨ, ਕਿਰਾਏ ਦੀ ਬੇਨਤੀ ਭੇਜ ਸਕਦੇ ਹਨ ਅਤੇ ਮਾਲਕ ਮਨਜ਼ੂਰ ਜਾਂ ਰੱਦ ਕਰ ਸਕਦੇ ਹਨ।',
    assistantRentHelp: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਸਾਂਝਾ ਖੋਲ੍ਹੋ, ਮਸ਼ੀਨ ਚੁਣੋ, ਕਿਰਾਏ ਤੇ ਲਵੋ ਦਬਾਓ, ਤਾਰੀਖਾਂ ਚੁਣੋ ਅਤੇ ਬੇਨਤੀ ਭੇਜੋ। ਮਾਲਕ ਦੀ ਮਨਜ਼ੂਰੀ ਲੋੜੀਂਦੀ ਹੈ।',
    assistantListHelp: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਸਾਂਝਾ ਖੋਲ੍ਹੋ ਅਤੇ ਲਿਸਟ ਕਰੋ ਚੁਣੋ। ਮਸ਼ੀਨ, ਥਾਂ, ਰੋਜ਼ਾਨਾ ਕਿਰਾਇਆ, ਜਮ੍ਹਾਂ ਅਤੇ ਉਪਲਬਧਤਾ ਭਰੋ।',
    assistantApprovalHelp: 'ਆਉਣ ਵਾਲੀਆਂ ਬੇਨਤੀਆਂ ਕਿਰਾਇਆ ਗਤੀਵਿਧੀ ਵਿੱਚ ਦਿਖਦੀਆਂ ਹਨ। ਪ੍ਰੋਫ਼ਾਈਲ ਕਾਰਡ ਤੋਂ ਮਾਲਕ ਤੇ ਜਾਓ, ਫਿਰ ਮਨਜ਼ੂਰ ਜਾਂ ਰੱਦ ਕਰੋ।',
    assistantStatusSummary: '{{incoming}} ਆਉਣ ਵਾਲੀਆਂ · {{outgoing}} ਭੇਜੀਆਂ · {{approved}} ਮਨਜ਼ੂਰ।', assistantCurrentUser: 'ਸਾਜ਼ੋ-ਸਾਮਾਨ ਡੈਮੋ ਖਾਤਾ: {{name}}।',
    assistantAvailable: 'ਹੁਣ ਉਪਲਬਧ: {{items}}।', assistantNoAvailable: 'ਇਸ ਵੇਲੇ ਕੋਈ ਮਿਲਦਾ ਸਾਜ਼ੋ-ਸਾਮਾਨ ਉਪਲਬਧ ਨਹੀਂ।'
  },
  or: {
    assistantTitle: 'ଉପକରଣ ଭାଗିଦାରୀ', openMarketplace: 'ଉପକରଣ ଭାଗିଦାରୀ ଖୋଲନ୍ତୁ', assistantIntroAddon: 'ମୁଁ କୃଷି ଯନ୍ତ୍ର ତାଲିକା, ଭଡ଼ା ଏବଂ ମାଲିକ ଅନୁମୋଦନରେ ମଧ୍ୟ ସାହାଯ୍ୟ କରିପାରିବି।',
    assistantOverview: 'ଚାଷୀମାନେ ଖାଲି ଯନ୍ତ୍ର ତାଲିକାଭୁକ୍ତ କରିପାରିବେ, ଉପଲବ୍ଧ ଉପକରଣ ଫିଲ୍ଟର କରିପାରିବେ, ଭଡ଼ା ଅନୁରୋଧ ପଠାଇପାରିବେ ଏବଂ ମାଲିକ ଅନୁମୋଦନ କିମ୍ବା ପ୍ରତ୍ୟାଖ୍ୟାନ କରିପାରିବେ।',
    assistantRentHelp: 'ଉପକରଣ ଭାଗିଦାରୀ ଖୋଲନ୍ତୁ, ଯନ୍ତ୍ର ବାଛନ୍ତୁ, ଭଡ଼ା ନିଅନ୍ତୁ ଦବାନ୍ତୁ, ତାରିଖ ବାଛି ଅନୁରୋଧ ପଠାନ୍ତୁ। ମାଲିକଙ୍କ ଅନୁମୋଦନ ଆବଶ୍ୟକ।',
    assistantListHelp: 'ଉପକରଣ ଭାଗିଦାରୀ ଖୋଲି ଉପକରଣ ତାଲିକାଭୁକ୍ତ କରନ୍ତୁ। ଯନ୍ତ୍ର, ସ୍ଥାନ, ଦୈନିକ ଭଡ଼ା, ଜମା ଓ ଉପଲବ୍ଧତା ଦିଅନ୍ତୁ।',
    assistantApprovalHelp: 'ଆସିଥିବା ଅନୁରୋଧ ଭଡ଼ା କାର୍ଯ୍ୟକଳାପରେ ଦେଖାଯାଏ। ପ୍ରୋଫାଇଲ କାର୍ଡରୁ ମାଲିକଙ୍କ ଖାତାକୁ ବଦଳାଇ ମଞ୍ଜୁର କିମ୍ବା ପ୍ରତ୍ୟାଖ୍ୟାନ ବାଛନ୍ତୁ।',
    assistantStatusSummary: '{{incoming}} ଆସିଥିବା · {{outgoing}} ପଠାଇଥିବା · {{approved}} ମଞ୍ଜୁର।', assistantCurrentUser: 'ଉପକରଣ ଡେମୋ ଖାତା: {{name}}।',
    assistantAvailable: 'ଏବେ ଉପଲବ୍ଧ: {{items}}।', assistantNoAvailable: 'ଏବେ କୌଣସି ମେଳ ଥିବା ଉପକରଣ ଉପଲବ୍ଧ ନାହିଁ।'
  },
  bn: {
    assistantTitle: 'যন্ত্র ভাগাভাগি', openMarketplace: 'যন্ত্র ভাগাভাগি খুলুন', assistantIntroAddon: 'আমি কৃষিযন্ত্রের তালিকা, ভাড়া এবং মালিকের অনুমোদনেও সাহায্য করতে পারি।',
    assistantOverview: 'কৃষকরা অব্যবহৃত যন্ত্র তালিকাভুক্ত করতে পারেন, উপলভ্য যন্ত্র ফিল্টার করতে পারেন, ভাড়ার অনুরোধ পাঠাতে পারেন এবং মালিক অনুরোধ অনুমোদন বা প্রত্যাখ্যান করতে পারেন।',
    assistantRentHelp: 'যন্ত্র ভাগাভাগি খুলুন, একটি যন্ত্র বেছে নিন, ভাড়া নিন চাপুন, তারিখ বেছে অনুরোধ পাঠান। মালিকের অনুমোদন দরকার।',
    assistantListHelp: 'যন্ত্র ভাগাভাগি খুলে যন্ত্র তালিকাভুক্ত করুন বেছে নিন। যন্ত্র, অবস্থান, দৈনিক ভাড়া, জামানত ও উপলভ্যতার তারিখ দিন।',
    assistantApprovalHelp: 'আসা অনুরোধ ভাড়া কার্যক্রমে দেখা যায়। প্রোফাইল কার্ড থেকে যন্ত্রের মালিক হিসেবে বদলান, তারপর অনুমোদন বা প্রত্যাখ্যান করুন।',
    assistantStatusSummary: '{{incoming}} আসা · {{outgoing}} পাঠানো · {{approved}} অনুমোদিত।', assistantCurrentUser: 'যন্ত্র ডেমো অ্যাকাউন্ট: {{name}}।',
    assistantAvailable: 'এখন উপলভ্য: {{items}}।', assistantNoAvailable: 'এখন কোনো মিল থাকা যন্ত্র উপলভ্য নেই।'
  },
  gu: {
    assistantTitle: 'સાધન શેરિંગ', openMarketplace: 'સાધન શેરિંગ ખોલો', assistantIntroAddon: 'હું કૃષિ સાધનોની સૂચિ, ભાડા અને માલિકની મંજૂરીમાં પણ મદદ કરી શકું છું.',
    assistantOverview: 'ખેડૂતો ખાલી મશીનરી સૂચિબદ્ધ કરી શકે છે, ઉપલબ્ધ સાધનો ફિલ્ટર કરી શકે છે, ભાડાની વિનંતી મોકલી શકે છે અને માલિક મંજૂર અથવા નકારી શકે છે.',
    assistantRentHelp: 'સાધન શેરિંગ ખોલો, મશીન પસંદ કરો, ભાડે લો દબાવો, તારીખો પસંદ કરી વિનંતી મોકલો. માલિકની મંજૂરી જરૂરી છે.',
    assistantListHelp: 'સાધન શેરિંગ ખોલો અને સાધન સૂચિબદ્ધ કરો પસંદ કરો. મશીન, સ્થળ, દૈનિક ભાડું, ડિપોઝિટ અને ઉપલબ્ધતા ઉમેરો.',
    assistantApprovalHelp: 'આવતી વિનંતીઓ ભાડા પ્રવૃત્તિમાં દેખાય છે. પ્રોફાઇલ કાર્ડથી સાધન માલિક પર સ્વિચ કરો, પછી મંજૂર અથવા નકારો.',
    assistantStatusSummary: '{{incoming}} આવતી · {{outgoing}} મોકલેલી · {{approved}} મંજૂર.', assistantCurrentUser: 'સાધન ડેમો એકાઉન્ટ: {{name}}.',
    assistantAvailable: 'હવે ઉપલબ્ધ: {{items}}.', assistantNoAvailable: 'હાલ કોઈ મેળ ખાતું સાધન ઉપલબ્ધ નથી.'
  },
  te: {
    assistantTitle: 'పరికరాల భాగస్వామ్యం', openMarketplace: 'పరికరాల భాగస్వామ్యం తెరవండి', assistantIntroAddon: 'వ్యవసాయ పరికరాల జాబితాలు, అద్దెలు మరియు యజమాని ఆమోదంలో కూడా సహాయం చేయగలను.',
    assistantOverview: 'రైతులు ఖాళీ యంత్రాలను జాబితా చేయవచ్చు, అందుబాటులో ఉన్న పరికరాలను ఫిల్టర్ చేయవచ్చు, అద్దె అభ్యర్థనలు పంపవచ్చు మరియు యజమానులు వాటిని ఆమోదించవచ్చు లేదా తిరస్కరించవచ్చు.',
    assistantRentHelp: 'పరికరాల భాగస్వామ్యం తెరవండి, యంత్రాన్ని ఎంచుకోండి, అద్దెకు తీసుకోండి నొక్కండి, తేదీలు ఎంచుకుని అభ్యర్థన పంపండి. యజమాని ఆమోదం అవసరం.',
    assistantListHelp: 'పరికరాల భాగస్వామ్యం తెరిచి పరికరం జాబితా చేయండి ఎంచుకోండి. యంత్రం, స్థలం, రోజువారీ అద్దె, డిపాజిట్ మరియు అందుబాటును నమోదు చేయండి.',
    assistantApprovalHelp: 'వచ్చిన అభ్యర్థనలు అద్దె కార్యకలాపంలో కనిపిస్తాయి. ప్రొఫైల్ కార్డు నుండి పరికర యజమానికి మారి, ఆమోదించు లేదా తిరస్కరించు ఎంచుకోండి.',
    assistantStatusSummary: '{{incoming}} వచ్చినవి · {{outgoing}} పంపినవి · {{approved}} ఆమోదిత.', assistantCurrentUser: 'పరికరాల డెమో ఖాతా: {{name}}.',
    assistantAvailable: 'ఇప్పుడు అందుబాటులో: {{items}}.', assistantNoAvailable: 'ప్రస్తుతం సరిపోలే పరికరం అందుబాటులో లేదు.'
  },
  ta: {
    assistantTitle: 'உபகரண பகிர்வு', openMarketplace: 'உபகரண பகிர்வைத் திற', assistantIntroAddon: 'வேளாண் உபகரண பட்டியல், வாடகை மற்றும் உரிமையாளர் ஒப்புதலிலும் நான் உதவ முடியும்.',
    assistantOverview: 'விவசாயிகள் பயன்படுத்தாத இயந்திரங்களை பட்டியலிடலாம், கிடைக்கும் உபகரணங்களை வடிகட்டலாம், வாடகை கோரிக்கை அனுப்பலாம்; உரிமையாளர்கள் அவற்றை ஒப்புதல் அல்லது நிராகரிக்கலாம்.',
    assistantRentHelp: 'உபகரண பகிர்வைத் திறந்து, இயந்திரத்தை தேர்வு செய்து, வாடகைக்கு எடு அழுத்தி, தேதிகளை தேர்வு செய்து கோரிக்கையை அனுப்புங்கள். உரிமையாளர் ஒப்புதல் தேவை.',
    assistantListHelp: 'உபகரண பகிர்வைத் திறந்து உபகரணம் பட்டியலிடு என்பதை தேர்வு செய்யுங்கள். இயந்திரம், இடம், தின வாடகை, வைப்பு மற்றும் கிடைக்கும் தேதிகளை சேர்க்கவும்.',
    assistantApprovalHelp: 'வரும் கோரிக்கைகள் வாடகை செயல்பாட்டில் தெரியும். சுயவிவர அட்டையிலிருந்து உபகரண உரிமையாளருக்கு மாறி, ஒப்புதல் அல்லது நிராகரி என்பதை தேர்வு செய்யுங்கள்.',
    assistantStatusSummary: '{{incoming}} வரும் · {{outgoing}} அனுப்பிய · {{approved}} ஒப்புதல்.', assistantCurrentUser: 'உபகரண டெமோ கணக்கு: {{name}}.',
    assistantAvailable: 'இப்போது கிடைக்கும்: {{items}}.', assistantNoAvailable: 'இப்போது பொருந்தும் உபகரணம் கிடைக்கவில்லை.'
  }
};

for (const [language, values] of Object.entries(assistantEquipmentTranslations)) {
  Object.assign(translations[language], values);
}

export default translations;
