const en = {
  demoData: 'DEMO DATA', notifications: 'Notifications', recentUpdates: '{{count}} recent updates', closeNotifications: 'Close notifications', reviewOffers: 'Review active offers', farmer: 'Farmer',
  bestMandiRate: 'Best mandi rate', nearbyMandi: 'Nearby mandi', perQuintal: 'per quintal', predictedPeak: 'Predicted peak', expectedSevenDays: 'Expected within the next 7 days', verifiedBuyerOffer: 'Verified buyer offer', noBuyer: 'No buyer', bestNetPrice: 'Your best net price', afterLogistics: 'After estimated logistics cost',
  smartPrediction: 'SMART SELL / HOLD · AI PREDICTION', sellNow: 'Sell now', holdBriefly: 'Hold briefly', sellDecision: 'Sell now · waiting does not improve estimated net', holdDecision: 'Hold {{days}} days for the expected peak', perQuintalNet: 'per quintal net', sellReason: 'Sell now; waiting does not improve the estimated net enough after storage and forecast uncertainty.', holdReason: 'Holding may improve the estimated net after storage cost.', forecastDisclaimer: 'Predicted from seeded historical data; not a live market guarantee.', currentPrice: 'Current price', forecastPeak: 'Forecast peak', bestNetOption: 'Best net option', rankingReason: 'Ranks price, distance, quantity fit and reliability.', hideCalculation: 'Hide calculation', whyRecommendation: 'Why this recommendation?', createALot: 'Create a lot',
  chartSevenDays: '7-day market movement', priceTrend: 'Price trend', rising: 'Rising', marketIntelligence: 'MARKET INTELLIGENCE · SIMULATED DATA', allMarkets: 'All {{crop}} markets', nearbyPrices: 'Nearby mandi prices', marketDataNote: 'Sample mandi prices for this prototype; connect an authorised market-data API before production.', showNearby: 'Show nearby', viewAllPrices: 'View all prices', mandiMarket: 'Mandi market', distance: 'Distance', modalPrice: 'Modal price', estimatedTransport: 'Est. transport/q', netPerQuintal: 'Net /q', nearby: 'Nearby',
  netComparison: 'NET REALISATION COMPARISON · ESTIMATED', chooseMore: 'Choose the option that leaves you with more', netDescription: 'Net figures include the available logistics estimate.', verifiedBuyer: 'Verified buyer', mandi: 'Mandi', net: 'net', earningsCalculator: 'NET EARNINGS CALCULATOR', receiveLot: 'What you could receive from this lot', earningsDescription: 'Net, storage and payout values come from the decision engine.', lotQuantity: 'Lot quantity', bestNet: 'Best net /q', storageEstimate: 'Storage estimate', includedInNet: 'Included in net /q', platformFee: 'Platform fee', farmerPayout: 'Estimated farmer payout',
  yourProduce: 'YOUR PRODUCE', lotsTitle: 'My crop lots', lotsDescription: 'Published lots and their matching offers appear here.', open: 'Open', closed: 'Closed', variety: 'Variety', notSpecified: 'Not specified', quality: 'Quality', grade: 'Grade', askingPrice: 'Asking price', harvested: 'Harvested', matchingOffers: '{{count}} matching offers waiting', lotClosed: 'Lot closed', findingMatches: 'Finding buyer matches', review: 'Review offers', close: 'Close', delete: 'Delete', noLots: 'No crop lots published yet', noLotsDescription: 'Create your first lot to start matching with buyers.',
  verifiedDemand: 'VERIFIED DEMAND · SIMULATED BUYERS', buyersMatched: 'Buyers matched for you', buyersNote: 'Buyer profiles and offers are simulated for the prototype.', hideRanking: 'Hide ranking guide', rankingGuide: 'How buyers are ranked', matchFormula: 'Match score formula', offerPrice: 'Offer price', quantityFit: 'Quantity fit', reliability: 'Reliability', rank: 'Rank', demoVerified: 'Demo verified', needs: 'Needs', indicativeOffer: 'Indicative offer', estimatedNet: 'Estimated net', matchScore: 'Match score', hideBreakdown: 'Hide match breakdown', viewBreakdown: 'View match breakdown',
  moveStore: 'MOVE AND STORE', logisticsOptions: 'Logistics options', transport: 'Transport', storage: 'Storage', capacity: 'Capacity', quintals: 'quintals', perDay: 'per quintal/day', select: 'Select', selected: 'Selected', selectedConfirmation: '{{provider}} is selected. Its estimated fee is included in the transaction breakdown.',
  orderStatus: 'ORDER STATUS', transactions: 'Transactions', demoBuyerOffer: 'Buyer offer', cropLot: 'Crop lot', buyerOffer: 'Buyer offer', pickupAvailable: 'Pickup available within 24 hours.', counter: 'Counter', decline: 'Decline', acceptOffer: 'Accept offer', counterSent: 'Counter sent', sendCounter: 'Send counter', nextStep: 'Next step', confirmPayment: 'Confirm payment received', downloadReceipt: 'Download receipt', pickup: 'Pickup', transit: 'Transit', delivery: 'Delivery', payment: 'Payment', noOffers: 'No active offers yet', noOffersDescription: 'Create a crop lot to start receiving buyer offers.',
  needHelp: 'NEED HELP?', raiseGrievance: 'Raise a grievance', reportIssue: 'Report an offer, logistics, quality, or payment issue.', describeConcern: 'Describe your concern', submit: 'Submit',
  sellProduce: 'SELL YOUR PRODUCE', createCropLot: 'Create a crop lot', optional: 'Optional', selectVariety: 'Select variety (optional)', qualityGrade: 'Quality grade', pickupLocation: 'Pickup location', harvestDate: 'Harvest date', dateHelp: 'Use the date picker', creatingLot: 'Creating lot…', publishLot: 'Publish crop lot', quantityError: 'Enter a whole quantity from 1 to 5,000 quintals.', language: 'Website language', standardText: 'Standard text', farmerMode: 'Farmer mode', dismiss: 'Dismiss message', day: 'Day {{count}}'
};

const compact = {
  hi: ['डेमो डेटा','सूचनाएँ','{{count}} हाल के अपडेट','सूचनाएँ बंद करें','सक्रिय ऑफर देखें','किसान','सर्वश्रेष्ठ मंडी भाव','नज़दीकी मंडी','प्रति क्विंटल','अनुमानित उच्च भाव','अगले 7 दिनों में अपेक्षित','सत्यापित खरीदार ऑफर','कोई खरीदार नहीं','आपका सर्वोत्तम शुद्ध भाव','अनुमानित परिवहन लागत के बाद','स्मार्ट बेचें / रोकें · एआई अनुमान','अभी बेचें','थोड़ा रोकें','अभी बेचें · प्रतीक्षा से शुद्ध लाभ नहीं बढ़ता','अपेक्षित उच्च भाव के लिए {{days}} दिन रोकें','प्रति क्विंटल शुद्ध','भंडारण और अनिश्चितता के बाद प्रतीक्षा लाभदायक नहीं है।','भंडारण लागत के बाद रोकने से लाभ बढ़ सकता है।','ऐतिहासिक नमूना डेटा से अनुमान; लाइव बाजार गारंटी नहीं।','वर्तमान भाव','अनुमानित उच्च भाव','सर्वोत्तम शुद्ध विकल्प','भाव, दूरी, मात्रा और विश्वसनीयता के आधार पर क्रम।','गणना छिपाएँ','यह सलाह क्यों?','लॉट बनाएँ','7-दिन बाजार चाल','भाव रुझान','बढ़ता','बाजार जानकारी · नमूना डेटा','सभी {{crop}} बाजार','नज़दीकी मंडी भाव','प्रोटोटाइप के नमूना भाव; उत्पादन से पहले अधिकृत API जोड़ें।','नज़दीकी दिखाएँ','सभी भाव देखें','मंडी बाजार','दूरी','मॉडल भाव','अनु. परिवहन/q','शुद्ध /q','नज़दीकी'],
  mr: ['डेमो डेटा','सूचना','{{count}} अलीकडील अपडेट','सूचना बंद करा','सक्रिय ऑफर पहा','शेतकरी','सर्वोत्तम मंडी भाव','जवळची मंडी','प्रति क्विंटल','अंदाजित उच्च भाव','पुढील 7 दिवसांत अपेक्षित','सत्यापित खरेदीदार ऑफर','खरेदीदार नाही','तुमचा सर्वोत्तम निव्वळ भाव','अंदाजित वाहतूक खर्चानंतर','स्मार्ट विक्री / थांबा · एआय अंदाज','आता विका','थोडे थांबा','आता विका · थांबल्याने निव्वळ फायदा वाढत नाही','अंदाजित उच्च भावासाठी {{days}} दिवस थांबा','प्रति क्विंटल निव्वळ','साठवण आणि अनिश्चिततेनंतर थांबणे फायदेशीर नाही.','साठवण खर्चानंतर थांबल्याने फायदा होऊ शकतो.','नमुना इतिहासावर आधारित अंदाज; थेट बाजार हमी नाही.','सध्याचा भाव','अंदाजित उच्च भाव','सर्वोत्तम निव्वळ पर्याय','भाव, अंतर, प्रमाण आणि विश्वासार्हतेनुसार क्रमवारी.','गणना लपवा','ही शिफारस का?','लॉट तयार करा','7-दिवस बाजार हालचाल','भाव कल','वाढता','बाजार माहिती · नमुना डेटा','सर्व {{crop}} बाजार','जवळचे मंडी भाव','प्रोटोटाइप नमुना भाव; उत्पादनासाठी अधिकृत API जोडा.','जवळचे दाखवा','सर्व भाव पहा','मंडी बाजार','अंतर','मॉडल भाव','अंदाजित वाहतूक/q','निव्वळ /q','जवळचे'],
  ur: ['ڈیمو ڈیٹا','اطلاعات','{{count}} حالیہ اپ ڈیٹس','اطلاعات بند کریں','فعال پیشکشیں دیکھیں','کسان','بہترین منڈی قیمت','قریبی منڈی','فی کوئنٹل','متوقع بلند قیمت','اگلے 7 دن میں متوقع','تصدیق شدہ خریدار پیشکش','کوئی خریدار نہیں','آپ کی بہترین خالص قیمت','تخمینی نقل و حمل کے بعد','سمارٹ فروخت / روکیں · اے آئی پیش گوئی','اب فروخت کریں','کچھ دیر روکیں','اب فروخت کریں · انتظار خالص فائدہ نہیں بڑھاتا','متوقع بلند قیمت کے لیے {{days}} دن روکیں','فی کوئنٹل خالص','ذخیرہ اور غیر یقینی کے بعد انتظار فائدہ مند نہیں۔','ذخیرہ لاگت کے بعد روکنا فائدہ دے سکتا ہے۔','نمونہ تاریخی ڈیٹا سے پیش گوئی؛ لائیو مارکیٹ ضمانت نہیں۔','موجودہ قیمت','متوقع بلند قیمت','بہترین خالص آپشن','قیمت، فاصلہ، مقدار اور اعتماد کے مطابق درجہ بندی۔','حساب چھپائیں','یہ سفارش کیوں؟','لاٹ بنائیں','7 دن کی مارکیٹ حرکت','قیمت کا رجحان','بڑھتا ہوا','مارکیٹ معلومات · نمونہ ڈیٹا','تمام {{crop}} مارکیٹیں','قریبی منڈی قیمتیں','پروٹوٹائپ نمونہ قیمتیں؛ پیداوار سے پہلے مجاز API جوڑیں۔','قریبی دکھائیں','تمام قیمتیں دیکھیں','منڈی مارکیٹ','فاصلہ','عام قیمت','تخمینی نقل و حمل/q','خالص /q','قریبی'],
  tr: ['DEMO VERİSİ','Bildirimler','{{count}} son güncelleme','Bildirimleri kapat','Aktif teklifleri incele','Çiftçi','En iyi pazar fiyatı','Yakındaki pazar','kental başına','Tahmini zirve','Önümüzdeki 7 gün içinde','Doğrulanmış alıcı teklifi','Alıcı yok','En iyi net fiyatınız','Tahmini lojistik sonrası','AKILLI SAT / BEKLE · YAPAY ZEKA TAHMİNİ','Şimdi sat','Kısa süre bekle','Şimdi sat · beklemek net kazancı artırmıyor','Beklenen zirve için {{days}} gün bekle','kental başına net','Depolama ve belirsizlikten sonra beklemek kazançlı değil.','Depolama sonrası beklemek kazancı artırabilir.','Örnek geçmiş veriden tahmin; canlı piyasa garantisi değildir.','Mevcut fiyat','Tahmini zirve','En iyi net seçenek','Fiyat, mesafe, miktar ve güvenilirliğe göre sıralar.','Hesabı gizle','Neden bu öneri?','Parti oluştur','7 günlük pazar hareketi','Fiyat eğilimi','Yükseliyor','PAZAR BİLGİSİ · ÖRNEK VERİ','Tüm {{crop}} pazarları','Yakındaki pazar fiyatları','Prototip örnek fiyatları; üretim öncesi yetkili API bağlayın.','Yakındakileri göster','Tüm fiyatları gör','Pazar','Mesafe','Ortalama fiyat','Tahmini taşıma/q','Net /q','Yakın'],
  es: ['DATOS DE DEMOSTRACIÓN','Notificaciones','{{count}} actualizaciones recientes','Cerrar notificaciones','Revisar ofertas activas','Agricultor','Mejor precio de mercado','Mercado cercano','por quintal','Pico previsto','Previsto en los próximos 7 días','Oferta de comprador verificado','Sin comprador','Tu mejor precio neto','Después de logística estimada','VENDER / ESPERAR · PREDICCIÓN IA','Vender ahora','Esperar brevemente','Vender ahora · esperar no mejora el neto','Esperar {{days}} días al pico previsto','neto por quintal','Esperar no compensa tras almacenamiento e incertidumbre.','Esperar puede mejorar el neto tras el almacenamiento.','Predicción con datos históricos de muestra; no garantiza el mercado real.','Precio actual','Pico previsto','Mejor opción neta','Ordena por precio, distancia, cantidad y fiabilidad.','Ocultar cálculo','¿Por qué esta recomendación?','Crear lote','Movimiento del mercado en 7 días','Tendencia de precio','Al alza','INTELIGENCIA DE MERCADO · DATOS SIMULADOS','Todos los mercados de {{crop}}','Precios de mercados cercanos','Precios de muestra; conecta una API autorizada antes de producción.','Mostrar cercanos','Ver todos los precios','Mercado','Distancia','Precio modal','Transporte est./q','Neto /q','Cercano'],
  pa: ['ਡੈਮੋ ਡਾਟਾ','ਸੂਚਨਾਵਾਂ','{{count}} ਨਵੇਂ ਅੱਪਡੇਟ','ਸੂਚਨਾਵਾਂ ਬੰਦ ਕਰੋ','ਸਰਗਰਮ ਪੇਸ਼ਕਸ਼ਾਂ ਵੇਖੋ','ਕਿਸਾਨ','ਸਭ ਤੋਂ ਵਧੀਆ ਮੰਡੀ ਭਾਅ','ਨੇੜਲੀ ਮੰਡੀ','ਪ੍ਰਤੀ ਕੁਇੰਟਲ','ਅਨੁਮਾਨਿਤ ਚੋਟੀ','ਅਗਲੇ 7 ਦਿਨਾਂ ਵਿੱਚ','ਪ੍ਰਮਾਣਿਤ ਖਰੀਦਦਾਰ ਪੇਸ਼ਕਸ਼','ਕੋਈ ਖਰੀਦਦਾਰ ਨਹੀਂ','ਤੁਹਾਡਾ ਵਧੀਆ ਸ਼ੁੱਧ ਭਾਅ','ਅਨੁਮਾਨਿਤ ਆਵਾਜਾਈ ਤੋਂ ਬਾਅਦ','ਸਮਾਰਟ ਵੇਚੋ / ਰੋਕੋ · ਏਆਈ ਅਨੁਮਾਨ','ਹੁਣ ਵੇਚੋ','ਥੋੜ੍ਹਾ ਰੋਕੋ','ਹੁਣ ਵੇਚੋ · ਉਡੀਕ ਨਾਲ ਸ਼ੁੱਧ ਲਾਭ ਨਹੀਂ ਵਧਦਾ','ਚੋਟੀ ਲਈ {{days}} ਦਿਨ ਰੋਕੋ','ਪ੍ਰਤੀ ਕੁਇੰਟਲ ਸ਼ੁੱਧ','ਸਟੋਰੇਜ ਤੋਂ ਬਾਅਦ ਉਡੀਕ ਲਾਭਦਾਇਕ ਨਹੀਂ।','ਰੋਕਣ ਨਾਲ ਲਾਭ ਵਧ ਸਕਦਾ ਹੈ।','ਨਮੂਨਾ ਡਾਟਾ ਅਨੁਮਾਨ; ਲਾਈਵ ਮੰਡੀ ਗਾਰੰਟੀ ਨਹੀਂ।','ਮੌਜੂਦਾ ਭਾਅ','ਅਨੁਮਾਨਿਤ ਚੋਟੀ','ਵਧੀਆ ਸ਼ੁੱਧ ਚੋਣ','ਭਾਅ, ਦੂਰੀ, ਮਾਤਰਾ ਅਤੇ ਭਰੋਸੇ ਅਨੁਸਾਰ ਦਰਜਾ।','ਗਣਨਾ ਲੁਕਾਓ','ਇਹ ਸਲਾਹ ਕਿਉਂ?','ਲਾਟ ਬਣਾਓ','7-ਦਿਨ ਮੰਡੀ ਚਾਲ','ਭਾਅ ਰੁਝਾਨ','ਵਧਦਾ','ਮੰਡੀ ਜਾਣਕਾਰੀ · ਨਮੂਨਾ ਡਾਟਾ','ਸਾਰੇ {{crop}} ਬਾਜ਼ਾਰ','ਨੇੜਲੇ ਮੰਡੀ ਭਾਅ','ਪ੍ਰੋਟੋਟਾਈਪ ਭਾਅ; ਅਧਿਕਾਰਤ API ਜੋੜੋ।','ਨੇੜਲੇ ਵੇਖੋ','ਸਾਰੇ ਭਾਅ ਵੇਖੋ','ਮੰਡੀ','ਦੂਰੀ','ਮਾਡਲ ਭਾਅ','ਅਨੁ. ਆਵਾਜਾਈ/q','ਸ਼ੁੱਧ /q','ਨੇੜੇ'],
  or: ['ଡେମୋ ତଥ୍ୟ','ବିଜ୍ଞପ୍ତି','{{count}} ସାମ୍ପ୍ରତିକ ଅପଡେଟ୍','ବିଜ୍ଞପ୍ତି ବନ୍ଦ','ସକ୍ରିୟ ଅଫର ଦେଖନ୍ତୁ','ଚାଷୀ','ସର୍ବୋତ୍ତମ ମଣ୍ଡି ଦର','ନିକଟ ମଣ୍ଡି','ପ୍ରତି କ୍ୱିଣ୍ଟାଲ','ଅନୁମାନିତ ସର୍ବୋଚ୍ଚ','ଆଗାମୀ 7 ଦିନରେ','ଯାଞ୍ଚିତ କ୍ରେତା ଅଫର','କ୍ରେତା ନାହିଁ','ଆପଣଙ୍କ ସର୍ବୋତ୍ତମ ନେଟ୍ ଦର','ଅନୁମାନିତ ପରିବହନ ପରେ','ସ୍ମାର୍ଟ ବିକ୍ରି / ରଖନ୍ତୁ · AI ଅନୁମାନ','ଏବେ ବିକ୍ରି','କିଛି ସମୟ ରଖନ୍ତୁ','ଏବେ ବିକ୍ରି · ଅପେକ୍ଷାରେ ନେଟ୍ ଲାଭ ବଢ଼େନି','ସର୍ବୋଚ୍ଚ ଦର ପାଇଁ {{days}} ଦିନ ରଖନ୍ତୁ','ପ୍ରତି କ୍ୱିଣ୍ଟାଲ ନେଟ୍','ସଂରକ୍ଷଣ ପରେ ଅପେକ୍ଷା ଲାଭଦାୟକ ନୁହେଁ।','ରଖିଲେ ନେଟ୍ ଲାଭ ବଢ଼ିପାରେ।','ନମୁନା ଇତିହାସ ଅନୁମାନ; ଲାଇଭ୍ ଦର ନୁହେଁ।','ବର୍ତ୍ତମାନ ଦର','ଅନୁମାନିତ ସର୍ବୋଚ୍ଚ','ସର୍ବୋତ୍ତମ ନେଟ୍ ବିକଳ୍ପ','ଦର, ଦୂରତା, ପରିମାଣ ଓ ଭରସା ଅନୁସାରେ।','ଗଣନା ଲୁଚାନ୍ତୁ','ଏହି ପରାମର୍ଶ କାହିଁକି?','ଲଟ୍ ତିଆରି','7-ଦିନ ବଜାର ଚଳନ','ଦର ପ୍ରବୃତ୍ତି','ବଢ଼ୁଛି','ବଜାର ସୂଚନା · ନମୁନା ତଥ୍ୟ','ସମସ୍ତ {{crop}} ବଜାର','ନିକଟ ମଣ୍ଡି ଦର','ପ୍ରୋଟୋଟାଇପ୍ ଦର; ଅଧିକୃତ API ଯୋଡନ୍ତୁ।','ନିକଟ ଦେଖନ୍ତୁ','ସବୁ ଦର ଦେଖନ୍ତୁ','ମଣ୍ଡି','ଦୂରତା','ମୋଡାଲ୍ ଦର','ଅନୁ. ପରିବହନ/q','ନେଟ୍ /q','ନିକଟ'],
  bn: ['ডেমো ডেটা','বিজ্ঞপ্তি','{{count}} সাম্প্রতিক আপডেট','বিজ্ঞপ্তি বন্ধ','সক্রিয় অফার দেখুন','কৃষক','সেরা বাজার দর','কাছের বাজার','প্রতি কুইন্টাল','পূর্বাভাসের সর্বোচ্চ','আগামী ৭ দিনের মধ্যে','যাচাইকৃত ক্রেতার অফার','ক্রেতা নেই','আপনার সেরা নিট দাম','আনুমানিক পরিবহনের পরে','স্মার্ট বিক্রি / অপেক্ষা · এআই পূর্বাভাস','এখন বিক্রি','অল্প অপেক্ষা','এখন বিক্রি · অপেক্ষায় নিট লাভ বাড়ে না','সর্বোচ্চ দামের জন্য {{days}} দিন অপেক্ষা','প্রতি কুইন্টাল নিট','সংরক্ষণের পরে অপেক্ষা লাভজনক নয়।','অপেক্ষায় নিট লাভ বাড়তে পারে।','নমুনা ইতিহাসের পূর্বাভাস; লাইভ বাজার নিশ্চয়তা নয়।','বর্তমান দাম','পূর্বাভাসের সর্বোচ্চ','সেরা নিট বিকল্প','দাম, দূরত্ব, পরিমাণ ও নির্ভরযোগ্যতা অনুযায়ী।','হিসাব লুকান','এই পরামর্শ কেন?','লট তৈরি','৭ দিনের বাজার পরিবর্তন','দামের প্রবণতা','ঊর্ধ্বমুখী','বাজার তথ্য · নমুনা ডেটা','সব {{crop}} বাজার','কাছের বাজার দর','প্রোটোটাইপ দর; অনুমোদিত API যুক্ত করুন।','কাছের দেখুন','সব দাম দেখুন','বাজার','দূরত্ব','মডাল দাম','আনু. পরিবহন/q','নিট /q','কাছের'],
  gu: ['ડેમો ડેટા','સૂચનાઓ','{{count}} તાજેતરના અપડેટ','સૂચનાઓ બંધ કરો','સક્રિય ઓફર જુઓ','ખેડૂત','શ્રેષ્ઠ બજાર ભાવ','નજીકની મંડી','પ્રતિ ક્વિન્ટલ','અનુમાનિત ટોચ','આગામી 7 દિવસમાં','ચકાસેલ ખરીદદાર ઓફર','ખરીદદાર નથી','તમારો શ્રેષ્ઠ નેટ ભાવ','અનુમાનિત પરિવહન પછી','સ્માર્ટ વેચો / રોકો · AI અનુમાન','હવે વેચો','થોડું રોકો','હવે વેચો · રાહ જોવાથી નેટ લાભ વધતો નથી','ટોચ માટે {{days}} દિવસ રોકો','પ્રતિ ક્વિન્ટલ નેટ','સંગ્રહ પછી રાહ લાભદાયી નથી.','રોકવાથી નેટ લાભ વધી શકે છે.','નમૂના ઇતિહાસનું અનુમાન; લાઇવ ભાવની ગેરંટી નહીં.','વર્તમાન ભાવ','અનુમાનિત ટોચ','શ્રેષ્ઠ નેટ વિકલ્પ','ભાવ, અંતર, જથ્થો અને વિશ્વસનીયતા અનુસાર.','ગણતરી છુપાવો','આ ભલામણ કેમ?','લોટ બનાવો','7 દિવસની બજાર ચાલ','ભાવ વલણ','વધતું','બજાર માહિતી · નમૂના ડેટા','બધા {{crop}} બજાર','નજીકના મંડી ભાવ','પ્રોટોટાઇપ ભાવ; અધિકૃત API જોડો.','નજીક બતાવો','બધા ભાવ જુઓ','મંડી','અંતર','મોડલ ભાવ','અનુ. પરિવહન/q','નેટ /q','નજીક'],
  te: ['డెమో డేటా','నోటిఫికేషన్లు','{{count}} తాజా నవీకరణలు','నోటిఫికేషన్లు మూసివేయి','క్రియాశీల ఆఫర్లు చూడండి','రైతు','ఉత్తమ మార్కెట్ ధర','సమీప మార్కెట్','క్వింటాల్‌కు','అంచనా గరిష్ఠం','రాబోయే 7 రోజుల్లో','ధృవీకరించిన కొనుగోలుదారు ఆఫర్','కొనుగోలుదారు లేరు','మీ ఉత్తమ నికర ధర','అంచనా రవాణా తర్వాత','స్మార్ట్ అమ్మకం / వేచి ఉండండి · AI అంచనా','ఇప్పుడే అమ్మండి','కొద్దిగా వేచి ఉండండి','ఇప్పుడే అమ్మండి · వేచి ఉండటం నికర లాభం పెంచదు','గరిష్ఠ ధరకు {{days}} రోజులు వేచి ఉండండి','క్వింటాల్‌కు నికర','నిల్వ తర్వాత వేచి ఉండటం లాభదాయకం కాదు.','వేచి ఉంటే నికర లాభం పెరగవచ్చు.','నమూనా చరిత్ర అంచనా; లైవ్ మార్కెట్ హామీ కాదు.','ప్రస్తుత ధర','అంచనా గరిష్ఠం','ఉత్తమ నికర ఎంపిక','ధర, దూరం, పరిమాణం, విశ్వసనీయత ఆధారంగా.','లెక్క దాచు','ఈ సిఫార్సు ఎందుకు?','లాట్ సృష్టించు','7 రోజుల మార్కెట్ మార్పు','ధర ధోరణి','పెరుగుతోంది','మార్కెట్ సమాచారం · నమూనా డేటా','అన్ని {{crop}} మార్కెట్లు','సమీప మార్కెట్ ధరలు','ప్రోటోటైప్ ధరలు; అధీకృత API జోడించండి.','సమీపం చూపు','అన్ని ధరలు చూడండి','మార్కెట్','దూరం','మోడల్ ధర','అంచనా రవాణా/q','నికర /q','సమీపం'],
  ta: ['டெமோ தரவு','அறிவிப்புகள்','{{count}} சமீப புதுப்பிப்புகள்','அறிவிப்புகளை மூடு','செயலில் உள்ள சலுகைகள்','விவசாயி','சிறந்த சந்தை விலை','அருகிலுள்ள சந்தை','குவிண்டாலுக்கு','கணிக்கப்பட்ட உச்சம்','அடுத்த 7 நாட்களில்','சரிபார்க்கப்பட்ட வாங்குபவர் சலுகை','வாங்குபவர் இல்லை','உங்கள் சிறந்த நிகர விலை','மதிப்பிடப்பட்ட போக்குவரத்துக்குப் பிறகு','ஸ்மார்ட் விற்பனை / காத்திரு · AI கணிப்பு','இப்போது விற்கவும்','சிறிது காத்திருங்கள்','இப்போது விற்கவும் · காத்திருப்பது நிகர லாபத்தை உயர்த்தாது','உச்ச விலைக்கு {{days}} நாட்கள் காத்திரு','குவிண்டாலுக்கு நிகர','சேமிப்புக்குப் பிறகு காத்திருப்பது பயனில்லை.','காத்திருப்பதால் நிகர லாபம் உயரலாம்.','மாதிரி வரலாறு கணிப்பு; நேரடி சந்தை உத்தரவாதம் அல்ல.','தற்போதைய விலை','கணிக்கப்பட்ட உச்சம்','சிறந்த நிகர தேர்வு','விலை, தூரம், அளவு, நம்பகத்தன்மைப்படி.','கணக்கை மறை','இந்த பரிந்துரை ஏன்?','தொகுதி உருவாக்கு','7 நாள் சந்தை மாற்றம்','விலை போக்கு','உயர்கிறது','சந்தை தகவல் · மாதிரி தரவு','அனைத்து {{crop}} சந்தைகள்','அருகிலுள்ள சந்தை விலைகள்','மாதிரி விலைகள்; அங்கீகரிக்கப்பட்ட API இணைக்கவும்.','அருகில் காட்டு','அனைத்து விலைகளும்','சந்தை','தூரம்','மாதிரி விலை','மதி. போக்குவரத்து/q','நிகர /q','அருகில்']
};

const compactKeys = Object.keys(en).slice(0, 48);
const result = { en };
for (const [language, values] of Object.entries(compact)) {
  result[language] = { ...en, ...Object.fromEntries(compactKeys.map((key, index) => [key, values[index]])) };
}

const wordKeys = ['lot','quantity','storage','fee','payout','produce','open','closed','variety','notSpecified','quality','grade','harvested','offers','review','close','delete','logistics','capacity','select','selected','transactions','counter','decline','accept','next','download','pickup','transit','delivery','payment','help','submit','optional','location','date','language','standard','farmerMode','dismiss','day','details'];
const wordSets = {
  hi: ['लॉट','मात्रा','भंडारण','शुल्क','किसान भुगतान','आपकी उपज','खुला','बंद','किस्म','निर्दिष्ट नहीं','गुणवत्ता','ग्रेड','कटाई','ऑफर','देखें','बंद करें','हटाएँ','परिवहन विकल्प','क्षमता','चुनें','चुना गया','लेन-देन','जवाबी भाव','अस्वीकार','स्वीकार','अगला कदम','रसीद डाउनलोड','पिकअप','रास्ते में','डिलीवरी','भुगतान','मदद','जमा करें','वैकल्पिक','स्थान','तारीख','भाषा','सामान्य पाठ','किसान मोड','संदेश बंद करें','दिन','विवरण'],
  mr: ['लॉट','प्रमाण','साठवण','शुल्क','शेतकरी देयक','तुमचे उत्पादन','खुले','बंद','प्रकार','नमूद नाही','गुणवत्ता','ग्रेड','कापणी','ऑफर','पहा','बंद करा','हटवा','वाहतूक पर्याय','क्षमता','निवडा','निवडले','व्यवहार','प्रतिऑफर','नकार','स्वीकार','पुढील पायरी','पावती डाउनलोड','उचल','प्रवासात','वितरण','देयक','मदत','सबमिट','ऐच्छिक','ठिकाण','तारीख','भाषा','सामान्य मजकूर','शेतकरी मोड','संदेश बंद','दिवस','तपशील'],
  ur: ['لاٹ','مقدار','ذخیرہ','فیس','کسان کی ادائیگی','آپ کی پیداوار','کھلا','بند','قسم','درج نہیں','معیار','گریڈ','کٹائی','پیشکشیں','دیکھیں','بند کریں','حذف کریں','نقل و حمل کے اختیارات','گنجائش','منتخب کریں','منتخب','لین دین','جوابی قیمت','مسترد','قبول','اگلا مرحلہ','رسید ڈاؤن لوڈ','اٹھان','راستے میں','ترسیل','ادائیگی','مدد','جمع کریں','اختیاری','مقام','تاریخ','زبان','عام متن','کسان موڈ','پیغام بند کریں','دن','تفصیل'],
  tr: ['parti','miktar','depolama','ücret','çiftçi ödemesi','ürününüz','açık','kapalı','çeşit','belirtilmedi','kalite','sınıf','hasat','teklifler','incele','kapat','sil','lojistik seçenekleri','kapasite','seç','seçildi','işlemler','karşı teklif','reddet','kabul et','sonraki adım','makbuzu indir','teslim alma','yolda','teslimat','ödeme','yardım','gönder','isteğe bağlı','konum','tarih','dil','standart metin','çiftçi modu','mesajı kapat','gün','ayrıntılar'],
  es: ['lote','cantidad','almacenamiento','tarifa','pago al agricultor','tu producción','abierto','cerrado','variedad','no especificado','calidad','grado','cosechado','ofertas','revisar','cerrar','eliminar','opciones logísticas','capacidad','seleccionar','seleccionado','transacciones','contraoferta','rechazar','aceptar','siguiente paso','descargar recibo','recogida','en tránsito','entrega','pago','ayuda','enviar','opcional','ubicación','fecha','idioma','texto estándar','modo agricultor','cerrar mensaje','día','detalles'],
  pa: ['ਲਾਟ','ਮਾਤਰਾ','ਸਟੋਰੇਜ','ਫੀਸ','ਕਿਸਾਨ ਭੁਗਤਾਨ','ਤੁਹਾਡੀ ਫਸਲ','ਖੁੱਲ੍ਹਾ','ਬੰਦ','ਕਿਸਮ','ਦਰਜ ਨਹੀਂ','ਗੁਣਵੱਤਾ','ਗ੍ਰੇਡ','ਕਟਾਈ','ਆਫਰ','ਵੇਖੋ','ਬੰਦ ਕਰੋ','ਹਟਾਓ','ਆਵਾਜਾਈ ਵਿਕਲਪ','ਸਮਰੱਥਾ','ਚੁਣੋ','ਚੁਣਿਆ','ਲੈਣ-ਦੇਣ','ਜਵਾਬੀ ਭਾਅ','ਰੱਦ','ਮਨਜ਼ੂਰ','ਅਗਲਾ ਕਦਮ','ਰਸੀਦ ਡਾਊਨਲੋਡ','ਚੁੱਕਣਾ','ਰਾਹ ਵਿੱਚ','ਡਿਲਿਵਰੀ','ਭੁਗਤਾਨ','ਮਦਦ','ਜਮ੍ਹਾਂ','ਵਿਕਲਪਿਕ','ਥਾਂ','ਤਾਰੀਖ','ਭਾਸ਼ਾ','ਆਮ ਲਿਖਤ','ਕਿਸਾਨ ਮੋਡ','ਸੁਨੇਹਾ ਬੰਦ','ਦਿਨ','ਵੇਰਵਾ'],
  or: ['ଲଟ୍','ପରିମାଣ','ସଂରକ୍ଷଣ','ଶୁଳ୍କ','ଚାଷୀ ପେମେଣ୍ଟ','ଆପଣଙ୍କ ଫସଲ','ଖୋଲା','ବନ୍ଦ','କିସମ','ଉଲ୍ଲେଖ ନାହିଁ','ଗୁଣବତ୍ତା','ଗ୍ରେଡ୍','ଅମଳ','ଅଫର୍','ଦେଖନ୍ତୁ','ବନ୍ଦ କରନ୍ତୁ','ହଟାନ୍ତୁ','ପରିବହନ ବିକଳ୍ପ','କ୍ଷମତା','ବାଛନ୍ତୁ','ବଛାଯାଇଛି','କାରବାର','ପ୍ରତି ଅଫର୍','ପ୍ରତ୍ୟାଖ୍ୟାନ','ଗ୍ରହଣ','ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ','ରସିଦ ଡାଉନଲୋଡ୍','ଉଠାଣ','ପଥରେ','ବିତରଣ','ପେମେଣ୍ଟ','ସାହାଯ୍ୟ','ଦାଖଲ','ଇଚ୍ଛାଧୀନ','ସ୍ଥାନ','ତାରିଖ','ଭାଷା','ସାଧାରଣ ପାଠ୍ୟ','ଚାଷୀ ମୋଡ୍','ସନ୍ଦେଶ ବନ୍ଦ','ଦିନ','ବିବରଣୀ'],
  bn: ['লট','পরিমাণ','সংরক্ষণ','ফি','কৃষক পেমেন্ট','আপনার ফসল','খোলা','বন্ধ','জাত','উল্লেখ নেই','গুণমান','গ্রেড','ফসল কাটা','অফার','দেখুন','বন্ধ করুন','মুছুন','পরিবহন বিকল্প','ধারণক্ষমতা','নির্বাচন','নির্বাচিত','লেনদেন','পাল্টা দাম','প্রত্যাখ্যান','গ্রহণ','পরবর্তী ধাপ','রসিদ ডাউনলোড','পিকআপ','পথে','ডেলিভারি','পেমেন্ট','সাহায্য','জমা দিন','ঐচ্ছিক','স্থান','তারিখ','ভাষা','সাধারণ লেখা','কৃষক মোড','বার্তা বন্ধ','দিন','বিবরণ'],
  gu: ['લોટ','જથ્થો','સંગ્રહ','ફી','ખેડૂત ચુકવણી','તમારો પાક','ખુલ્લું','બંધ','જાત','ઉલ્લેખ નથી','ગુણવત્તા','ગ્રેડ','લણણી','ઓફર','જુઓ','બંધ કરો','કાઢી નાખો','પરિવહન વિકલ્પ','ક્ષમતા','પસંદ કરો','પસંદ કરેલ','વ્યવહારો','સામો ભાવ','નકારો','સ્વીકારો','આગલું પગલું','રસીદ ડાઉનલોડ','પિકઅપ','માર્ગમાં','ડિલિવરી','ચુકવણી','મદદ','સબમિટ','વૈકલ્પિક','સ્થળ','તારીખ','ભાષા','સામાન્ય લખાણ','ખેડૂત મોડ','સંદેશ બંધ','દિવસ','વિગતો'],
  te: ['లాట్','పరిమాణం','నిల్వ','రుసుము','రైతు చెల్లింపు','మీ పంట','తెరిచి ఉంది','మూసివేసింది','రకం','పేర్కొనలేదు','నాణ్యత','గ్రేడ్','కోత','ఆఫర్లు','చూడండి','మూసివేయి','తొలగించు','రవాణా ఎంపికలు','సామర్థ్యం','ఎంచుకోండి','ఎంచుకున్నారు','లావాదేవీలు','ప్రతి ఆఫర్','తిరస్కరించు','అంగీకరించు','తదుపరి దశ','రసీదు డౌన్‌లోడ్','పికప్','రవాణాలో','డెలివరీ','చెల్లింపు','సహాయం','సమర్పించు','ఐచ్ఛికం','స్థలం','తేదీ','భాష','సాధారణ వచనం','రైతు మోడ్','సందేశం మూసివేయి','రోజు','వివరాలు'],
  ta: ['தொகுதி','அளவு','சேமிப்பு','கட்டணம்','விவசாயி பணம்','உங்கள் விளைபொருள்','திறந்தது','மூடப்பட்டது','வகை','குறிப்பிடவில்லை','தரம்','கிரேடு','அறுவடை','சலுகைகள்','பார்க்க','மூடு','நீக்கு','போக்குவரத்து விருப்பங்கள்','கொள்ளளவு','தேர்வு','தேர்ந்தெடுக்கப்பட்டது','பரிவர்த்தனைகள்','எதிர் விலை','நிராகரி','ஏற்க','அடுத்த படி','ரசீது பதிவிறக்கம்','எடுத்தல்','பயணத்தில்','விநியோகம்','பணம்','உதவி','சமர்ப்பி','விருப்பம்','இடம்','தேதி','மொழி','இயல்பான எழுத்து','விவசாயி முறை','செய்தியை மூடு','நாள்','விவரங்கள்']
};

function completePage(page, words) {
  const w = Object.fromEntries(wordKeys.map((key, index) => [key, words[index]]));
  Object.assign(page, {
    netComparison: `${page.bestNetOption} · ${page.netPerQuintal}`, chooseMore: page.bestNetOption, netDescription: page.rankingReason,
    verifiedBuyer: page.verifiedBuyerOffer, mandi: page.nearbyMandi, net: page.bestNetPrice, earningsCalculator: page.bestNetOption,
    receiveLot: `${w.payout} · ${w.lot}`, earningsDescription: w.details, lotQuantity: `${w.lot} ${w.quantity}`, bestNet: page.bestNetPrice,
    storageEstimate: `${w.storage} ${page.estimatedTransport}`, includedInNet: page.afterLogistics, platformFee: w.fee, farmerPayout: w.payout,
    yourProduce: w.produce, lotsTitle: w.produce, lotsDescription: w.details, open: w.open, closed: w.closed, variety: w.variety,
    notSpecified: w.notSpecified, quality: w.quality, grade: w.grade, askingPrice: page.currentPrice, harvested: w.harvested,
    matchingOffers: `{{count}} ${w.offers}`, lotClosed: `${w.lot} ${w.closed}`, findingMatches: page.rankingReason, review: w.review,
    close: w.close, delete: w.delete, noLots: `${w.lot} — ${w.notSpecified}`, noLotsDescription: `${page.createALot} · ${w.offers}`,
    verifiedDemand: page.verifiedBuyerOffer, buyersMatched: page.rankingReason, buyersNote: page.forecastDisclaimer,
    hideRanking: page.hideCalculation, rankingGuide: page.rankingReason, matchFormula: page.rankingReason, offerPrice: page.currentPrice,
    quantityFit: w.quantity, reliability: page.rankingReason, rank: page.bestNetOption, demoVerified: page.verifiedBuyerOffer,
    needs: w.quantity, indicativeOffer: page.verifiedBuyerOffer, estimatedNet: page.bestNetPrice, matchScore: page.rankingReason,
    hideBreakdown: page.hideCalculation, viewBreakdown: w.details, moveStore: `${w.logistics} · ${w.storage}`, logisticsOptions: w.logistics,
    transport: page.estimatedTransport, storage: w.storage, capacity: w.capacity, quintals: page.perQuintal, perDay: `${page.perQuintal} / ${w.day}`,
    select: w.select, selected: w.selected, selectedConfirmation: `{{provider}} · ${w.selected}`, orderStatus: w.transactions,
    transactions: w.transactions, demoBuyerOffer: page.verifiedBuyerOffer, cropLot: w.lot, buyerOffer: page.verifiedBuyerOffer,
    pickupAvailable: w.pickup, counter: w.counter, decline: w.decline, acceptOffer: `${w.accept} ${w.offers}`, counterSent: `${w.counter} · ${w.selected}`,
    sendCounter: `${w.submit} ${w.counter}`, nextStep: w.next, confirmPayment: `${w.accept} ${w.payment}`, downloadReceipt: w.download,
    pickup: w.pickup, transit: w.transit, delivery: w.delivery, payment: w.payment, noOffers: `${w.offers} — ${w.notSpecified}`,
    noOffersDescription: `${page.createALot} · ${w.offers}`, needHelp: w.help, raiseGrievance: w.help, reportIssue: w.details,
    describeConcern: w.details, submit: w.submit, sellProduce: w.produce, createCropLot: page.createALot, optional: w.optional,
    selectVariety: `${w.select} ${w.variety}`, qualityGrade: `${w.quality} ${w.grade}`, pickupLocation: `${w.pickup} ${w.location}`,
    harvestDate: `${w.harvested} ${w.date}`, dateHelp: w.date, creatingLot: `${page.createALot}…`, publishLot: page.createALot,
    quantityError: `${w.quantity}: 1–5,000`, language: w.language, standardText: w.standard, farmerMode: w.farmerMode,
    dismiss: w.dismiss, day: `${w.day} {{count}}`
  });
}

for (const [language, words] of Object.entries(wordSets)) completePage(result[language], words);

Object.assign(result.ur, {
  orderStatus: 'آرڈر کی صورتحال',
  transactions: 'لین دین',
  needHelp: 'مدد چاہیے؟',
  raiseGrievance: 'شکایت درج کریں',
  reportIssue: 'آفر، نقل و حمل، معیار یا ادائیگی سے متعلق مسئلہ رپورٹ کریں۔',
  describeConcern: 'اپنا مسئلہ لکھیں',
  submit: 'جمع کریں',
  pickupAvailable: 'اٹھان 24 گھنٹوں کے اندر دستیاب ہے۔'
});

export default result;
